"""Catálogo médico nacional usado por SIGARH y la aplicación hospitalaria.

Nomenclatura: Anexo 1 de las Disposiciones Complementarias CONAREME 2026.
La categoría hospitalaria solo genera una recomendación inicial; la cartera real
de cada IPRESS se confirma en ``sigarh_especialidades.is_active``.
"""

from __future__ import annotations

import uuid


FUENTE = "CONAREME"
NORMA = "Disposiciones Complementarias del Concurso Nacional de Admisión 2026 - Anexo 1"
FUENTE_URL = "https://www.conareme.org.pe/web/Documentos/Admision2026/Disposiciones%20Complementarias..pdf"
NAMESPACE = uuid.UUID("b50e47a8-44fc-4b2c-bf88-b01fd58b3c57")


ESPECIALIDADES = [
    "ADMINISTRACIÓN Y GESTIÓN EN SALUD",
    "ADOLESCENTOLOGÍA",
    "ANATOMÍA PATOLÓGICA",
    "ANESTESIOLOGÍA",
    "CARDIOLOGÍA",
    "CIRUGÍA DE CABEZA, CUELLO Y MAXILOFACIAL",
    "CIRUGÍA DE TÓRAX Y CARDIOVASCULAR",
    "CIRUGÍA GENERAL",
    "CIRUGÍA ONCOLÓGICA",
    "CIRUGÍA PEDIÁTRICA",
    "CIRUGÍA PLÁSTICA",
    "DERMATOLOGÍA",
    "ENDOCRINOLOGÍA",
    "GASTROENTEROLOGÍA",
    "GENÉTICA MÉDICA",
    "GERIATRÍA",
    "GINECOLOGÍA Y OBSTETRICIA",
    "HEMATOLOGÍA",
    "INMUNOLOGÍA Y ALERGIA",
    "MEDICINA DE EMERGENCIAS Y DESASTRES",
    "MEDICINA DE ENFERMEDADES INFECCIOSAS Y TROPICALES",
    "MEDICINA DEL DEPORTE",
    "MEDICINA FAMILIAR Y COMUNITARIA",
    "MEDICINA FÍSICA Y DE REHABILITACIÓN",
    "MEDICINA INTENSIVA",
    "MEDICINA INTERNA",
    "MEDICINA LEGAL",
    "MEDICINA NUCLEAR",
    "MEDICINA OCUPACIONAL Y DEL MEDIO AMBIENTE",
    "MEDICINA ONCOLÓGICA",
    "NEFROLOGÍA",
    "NEUMOLOGÍA",
    "NEUROCIRUGÍA",
    "NEUROLOGÍA",
    "OFTALMOLOGÍA",
    "ORTOPEDIA Y TRAUMATOLOGÍA",
    "OTORRINOLARINGOLOGÍA",
    "PATOLOGÍA CLÍNICA",
    "PEDIATRÍA",
    "PSIQUIATRÍA",
    "RADIOLOGÍA",
    "RADIOTERAPIA",
    "REUMATOLOGÍA",
    "UROLOGÍA",
]

# (nombre, especialidad principal, requisitos admitidos por CONAREME)
SUBESPECIALIDADES = [
    ("ANESTESIOLOGÍA CARDIOVASCULAR", "ANESTESIOLOGÍA", ["ANESTESIOLOGÍA"]),
    ("ANESTESIOLOGÍA OBSTÉTRICA", "ANESTESIOLOGÍA", ["ANESTESIOLOGÍA"]),
    (
        "ANESTESIOLOGÍA Y TERAPIA INTENSIVA CARDIOVASCULAR",
        "ANESTESIOLOGÍA",
        ["ANESTESIOLOGÍA"],
    ),
    ("CARDIOLOGÍA PEDIÁTRICA", "PEDIATRÍA", ["PEDIATRÍA"]),
    (
        "CIRUGÍA CARDIOVASCULAR PEDIÁTRICA",
        "CIRUGÍA DE TÓRAX Y CARDIOVASCULAR",
        ["CIRUGÍA DE TÓRAX Y CARDIOVASCULAR"],
    ),
    ("CIRUGÍA DE TÓRAX Y CARDIOVASCULAR", "CIRUGÍA GENERAL", ["CIRUGÍA GENERAL"]),
    ("CIRUGÍA DE COLON, RECTO Y ANO", "CIRUGÍA GENERAL", ["CIRUGÍA GENERAL"]),
    (
        "CIRUGÍA DE MANO",
        "CIRUGÍA PLÁSTICA",
        ["CIRUGÍA PLÁSTICA", "ORTOPEDIA Y TRAUMATOLOGÍA"],
    ),
    ("CIRUGÍA DE RETINA Y VÍTREO", "OFTALMOLOGÍA", ["OFTALMOLOGÍA"]),
    (
        "CIRUGÍA DE TÓRAX ONCOLÓGICA",
        "CIRUGÍA ONCOLÓGICA",
        ["CIRUGÍA ONCOLÓGICA", "CIRUGÍA DE TÓRAX Y CARDIOVASCULAR"],
    ),
    (
        "CIRUGÍA HEPATOPANCREATOBILIAR Y TRASPLANTE",
        "CIRUGÍA GENERAL",
        ["CIRUGÍA GENERAL", "CIRUGÍA ONCOLÓGICA"],
    ),
    (
        "CIRUGÍA ONCOLÓGICA ABDOMINAL",
        "CIRUGÍA ONCOLÓGICA",
        ["CIRUGÍA GENERAL", "CIRUGÍA ONCOLÓGICA"],
    ),
    (
        "CIRUGÍA ONCOLÓGICA DE CABEZA Y CUELLO",
        "CIRUGÍA ONCOLÓGICA",
        ["CIRUGÍA DE CABEZA, CUELLO Y MAXILOFACIAL", "CIRUGÍA ONCOLÓGICA"],
    ),
    (
        "CIRUGÍA ONCOLÓGICA DE MAMAS, TEJIDOS BLANDOS Y PIEL",
        "CIRUGÍA ONCOLÓGICA",
        ["CIRUGÍA GENERAL", "CIRUGÍA ONCOLÓGICA"],
    ),
    ("CIRUGÍA PEDIÁTRICA", "CIRUGÍA GENERAL", ["CIRUGÍA GENERAL"]),
    ("CIRUGÍA PLÁSTICA Y RECONSTRUCTIVA", "CIRUGÍA GENERAL", ["CIRUGÍA GENERAL"]),
    ("DERMATOLOGÍA PEDIÁTRICA", "DERMATOLOGÍA", ["DERMATOLOGÍA", "PEDIATRÍA"]),
    ("EMERGENCIAS PEDIÁTRICAS", "PEDIATRÍA", ["PEDIATRÍA"]),
    ("ENDOCRINOLOGÍA PEDIÁTRICA", "PEDIATRÍA", ["PEDIATRÍA"]),
    ("GASTROENTEROLOGÍA PEDIÁTRICA", "PEDIATRÍA", ["PEDIATRÍA"]),
    (
        "GINECOLOGÍA ONCOLÓGICA",
        "GINECOLOGÍA Y OBSTETRICIA",
        ["GINECOLOGÍA Y OBSTETRICIA", "CIRUGÍA ONCOLÓGICA"],
    ),
    ("HEMATOLOGÍA PEDIÁTRICA", "PEDIATRÍA", ["HEMATOLOGÍA", "PEDIATRÍA"]),
    ("INFECTOLOGÍA PEDIÁTRICA", "PEDIATRÍA", ["PEDIATRÍA"]),
    ("MEDICINA INTENSIVA PEDIÁTRICA", "PEDIATRÍA", ["PEDIATRÍA"]),
    ("NEFROLOGÍA PEDIÁTRICA", "PEDIATRÍA", ["PEDIATRÍA"]),
    ("NEONATOLOGÍA", "PEDIATRÍA", ["PEDIATRÍA"]),
    ("NEUMOLOGÍA ONCOLÓGICA", "NEUMOLOGÍA", ["NEUMOLOGÍA"]),
    ("NEUMOLOGÍA PEDIÁTRICA", "PEDIATRÍA", ["PEDIATRÍA"]),
    ("NEUROCIRUGÍA PEDIÁTRICA", "NEUROCIRUGÍA", ["NEUROCIRUGÍA"]),
    ("NEUROLOGÍA PEDIÁTRICA", "PEDIATRÍA", ["PEDIATRÍA"]),
    ("OFTALMOLOGÍA ONCOLÓGICA", "OFTALMOLOGÍA", ["OFTALMOLOGÍA"]),
    ("OFTALMOLOGÍA PEDIÁTRICA Y ESTRABISMO", "OFTALMOLOGÍA", ["OFTALMOLOGÍA"]),
    ("ONCOLOGÍA PEDIÁTRICA", "PEDIATRÍA", ["PEDIATRÍA"]),
    (
        "PATOLOGÍA ONCOLÓGICA",
        "ANATOMÍA PATOLÓGICA",
        ["ANATOMÍA PATOLÓGICA", "PATOLOGÍA CLÍNICA"],
    ),
    ("PEDIATRÍA DE EMERGENCIAS Y DESASTRES", "PEDIATRÍA", ["PEDIATRÍA"]),
    ("PSIQUIATRÍA DE ADICCIONES", "PSIQUIATRÍA", ["PSIQUIATRÍA"]),
    ("PSIQUIATRÍA DEL NIÑO Y DEL ADOLESCENTE", "PSIQUIATRÍA", ["PSIQUIATRÍA"]),
    ("RADIOLOGÍA INTERVENCIONISTA", "RADIOLOGÍA", ["RADIOLOGÍA"]),
    ("UROLOGÍA ONCOLÓGICA", "UROLOGÍA", ["UROLOGÍA", "CIRUGÍA ONCOLÓGICA"]),
    ("UROLOGÍA PEDIÁTRICA", "UROLOGÍA", ["UROLOGÍA"]),
]

RECOMENDADAS_POR_NIVEL = {
    "II-1": {
        "ANESTESIOLOGÍA",
        "CIRUGÍA GENERAL",
        "GINECOLOGÍA Y OBSTETRICIA",
        "MEDICINA INTERNA",
        "PEDIATRÍA",
    },
    "II-2": {
        "ANATOMÍA PATOLÓGICA",
        "ANESTESIOLOGÍA",
        "CARDIOLOGÍA",
        "CIRUGÍA GENERAL",
        "DERMATOLOGÍA",
        "GASTROENTEROLOGÍA",
        "GINECOLOGÍA Y OBSTETRICIA",
        "MEDICINA DE EMERGENCIAS Y DESASTRES",
        "MEDICINA FÍSICA Y DE REHABILITACIÓN",
        "MEDICINA INTERNA",
        "NEFROLOGÍA",
        "NEUMOLOGÍA",
        "NEUROLOGÍA",
        "OFTALMOLOGÍA",
        "ORTOPEDIA Y TRAUMATOLOGÍA",
        "OTORRINOLARINGOLOGÍA",
        "PATOLOGÍA CLÍNICA",
        "PEDIATRÍA",
        "PSIQUIATRÍA",
        "RADIOLOGÍA",
        "REUMATOLOGÍA",
        "UROLOGÍA",
    },
}
RECOMENDADAS_POR_NIVEL["III-1"] = RECOMENDADAS_POR_NIVEL["II-2"] | {
    "CIRUGÍA DE CABEZA, CUELLO Y MAXILOFACIAL",
    "CIRUGÍA DE TÓRAX Y CARDIOVASCULAR",
    "CIRUGÍA ONCOLÓGICA",
    "CIRUGÍA PEDIÁTRICA",
    "CIRUGÍA PLÁSTICA",
    "ENDOCRINOLOGÍA",
    "HEMATOLOGÍA",
    "MEDICINA INTENSIVA",
    "MEDICINA ONCOLÓGICA",
    "NEUROCIRUGÍA",
}
RECOMENDADAS_POR_NIVEL["III-2"] = set(ESPECIALIDADES)
RECOMENDADAS_POR_NIVEL["III-E"] = set(ESPECIALIDADES)


def catalogo_id(tipo: str, nombre: str) -> uuid.UUID:
    return uuid.uuid5(NAMESPACE, f"{tipo}:{nombre}")


def oferta_id(tenant_id: uuid.UUID, catalog_id: uuid.UUID) -> uuid.UUID:
    return uuid.uuid5(NAMESPACE, f"oferta:{tenant_id}:{catalog_id}")


def codigo(tipo: str, numero: int) -> str:
    return f"CON-{tipo[:3].upper()}-{numero:03d}"
