<script setup lang="ts">
definePageMeta({ layout: 'app', middleware: ['auth'] })
const { api } = useApi(); const { link } = useHospitalNav()
const items = ref<any[]>([]); const loading = ref(true); const error = ref(''); const search = ref(''); const destino = ref('')
const destinos = ['AMBULATORIA','HOSPITALIZACION','REFERENCIA','INTERCONSULTA','ALTA','FALLECIDO']
const labels:Record<string,string>={AMBULATORIA:'Atención ambulatoria',HOSPITALIZACION:'Hospitalización',REFERENCIA:'Referencia',INTERCONSULTA:'Interconsulta',ALTA:'Alta',FALLECIDO:'Fallecido'}
const filtered=computed(()=>items.value.filter(i=>(!destino.value||i.destino_atencion===destino.value)&&(!search.value.trim()||[i.paciente_nombre,i.numero_cuenta].join(' ').toLowerCase().includes(search.value.toLowerCase().trim()))))
async function cargar(){loading.value=true;error.value='';try{items.value=await api('/app/emergencia/atenciones')}catch(e:any){error.value=e?.data?.detail||'No se pudieron cargar las atenciones'}finally{loading.value=false}}
onMounted(cargar)
</script>
<template><div class="p-6 space-y-5"><div><h1 class="text-2xl font-bold">Atenciones de emergencia</h1><p class="text-sm" style="color:var(--ink-soft)">Seguimiento desde la admisión hasta el destino clínico</p></div><div class="p-4 flex flex-wrap gap-3 card"><input v-model="search" class="field" placeholder="Paciente o número de cuenta"><select v-model="destino" class="field"><option value="">Todos los destinos</option><option v-for="d in destinos" :key="d" :value="d">{{labels[d]}}</option></select><button class="action" @click="cargar">Actualizar</button></div><div v-if="error" class="error">{{error}}</div><div class="card overflow-x-auto"><div v-if="loading" class="p-10 text-center">Cargando...</div><table v-else class="w-full text-sm"><thead><tr><th>Cuenta</th><th>Paciente</th><th>Prioridad</th><th>Motivo</th><th>Destino</th><th>Firma</th><th>Derivación</th><th>Acción</th></tr></thead><tbody><tr v-for="i in filtered" :key="i.id"><td class="font-mono">{{i.numero_cuenta}}</td><td>{{i.paciente_nombre}}</td><td>{{i.prioridad||'—'}}</td><td>{{i.motivo_consulta}}</td><td>{{labels[i.destino_atencion]}}</td><td>{{i.estado==='firmado'?'Firmada':'Borrador'}}</td><td>{{i.destino_estado||'Pendiente de firma'}}</td><td><NuxtLink :to="link('/app/emergencia/atencion/'+i.admision_id)" style="color:var(--teal)">Ver</NuxtLink></td></tr><tr v-if="!filtered.length"><td colspan="8" class="p-10 text-center">No hay atenciones</td></tr></tbody></table></div></div></template>
<style scoped>.card{background:var(--paper);border:1px solid var(--line);border-radius:var(--radius-lg)}.field{padding:.65rem;border:1px solid var(--line);border-radius:8px;min-width:240px}.action{padding:.65rem 1rem;background:var(--teal);color:white;border-radius:8px}.error{padding:1rem;background:var(--alert-soft);color:var(--alert);border-radius:8px}th,td{padding:.8rem;text-align:left;border-bottom:1px solid var(--line)}</style>
