<script setup lang="ts">
const props=defineProps<{destino:string;titulo:string;descripcion?:string}>(); const {api}=useApi(); const {link}=useHospitalNav()
const items=ref<any[]>([]);const loading=ref(true);const error=ref('');const resolving=ref('')
async function cargar(){loading.value=true;error.value='';try{items.value=await api('/app/emergencia/destinos?destino='+props.destino)}catch(e:any){error.value=e?.data?.detail||'No se pudo cargar la cola'}finally{loading.value=false}}
async function resolver(i:any){resolving.value=i.id;try{await api('/app/emergencia/destinos/'+i.id+'/resolver',{method:'POST',body:{observacion:'Destino atendido'}});await cargar()}catch(e:any){error.value=e?.data?.detail||'No se pudo completar'}finally{resolving.value=''}}
onMounted(cargar)
</script>
<template><div class="p-6 space-y-5"><div><h1 class="text-2xl font-bold">{{titulo}}</h1><p class="text-sm" style="color:var(--ink-soft)">Derivaciones generadas desde atenciones firmadas</p></div><div v-if="error" style="color:var(--alert)">{{error}}</div><div class="box overflow-x-auto"><div v-if="loading" class="p-10 text-center">Cargando...</div><table v-else class="w-full text-sm"><thead><tr><th>Cuenta</th><th>Paciente</th><th>Estado</th><th>Fecha</th><th>Acción</th></tr></thead><tbody><tr v-for="i in items" :key="i.id"><td class="font-mono">{{i.numero_cuenta}}</td><td>{{i.paciente_nombre}}</td><td>{{i.estado}}</td><td>{{new Date(i.created_at).toLocaleString('es-PE')}}</td><td><NuxtLink :to="link('/app/emergencia/atencion/'+i.admision_id)" class="mr-3" style="color:var(--teal)">Ver</NuxtLink><button v-if="i.estado==='pendiente'" :disabled="resolving===i.id" style="color:var(--green)" @click="resolver(i)">Completar</button></td></tr><tr v-if="!items.length"><td colspan="5" class="p-10 text-center">Sin derivaciones</td></tr></tbody></table></div></div></template>
<style scoped>.box{background:var(--paper);border:1px solid var(--line);border-radius:var(--radius-lg)}th,td{padding:.8rem;text-align:left;border-bottom:1px solid var(--line)}</style>
