"""crear tablas sigarh roles de turno

Revision ID: 015c1d94ffb7
Revises: eb38ca19b28e
Create Date: 2026-09-08 17:43:54.040017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '015c1d94ffb7'
down_revision: Union[str, Sequence[str], None] = 'eb38ca19b28e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_roles_turno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('categoria_personal', sa.String(length=30), nullable=False),
    sa.Column('tipo_rol', sa.String(length=40), nullable=False),
    sa.Column('departamento_id', sa.UUID(), nullable=True),
    sa.Column('servicio_id', sa.UUID(), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['sigarh_departamentos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['sigarh_servicios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_roles_turno_anio'), 'sigarh_roles_turno', ['anio'], unique=False)
    op.create_index(op.f('ix_sigarh_roles_turno_categoria_personal'), 'sigarh_roles_turno', ['categoria_personal'], unique=False)
    op.create_index(op.f('ix_sigarh_roles_turno_status'), 'sigarh_roles_turno', ['status'], unique=False)
    op.create_index(op.f('ix_sigarh_roles_turno_tenant_id'), 'sigarh_roles_turno', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sigarh_roles_turno_tipo_rol'), 'sigarh_roles_turno', ['tipo_rol'], unique=False)
    op.create_table('sigarh_roles_turno_empleados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['sigarh_empleados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['sigarh_roles_turno.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_roles_turno_empleados_rol_id'), 'sigarh_roles_turno_empleados', ['rol_id'], unique=False)
    op.create_table('sigarh_roles_turno_solicitudes_mod',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('schedule_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['sigarh_empleados.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rol_id'], ['sigarh_roles_turno.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_roles_turno_solicitudes_mod_rol_id'), 'sigarh_roles_turno_solicitudes_mod', ['rol_id'], unique=False)
    op.create_index(op.f('ix_sigarh_roles_turno_solicitudes_mod_status'), 'sigarh_roles_turno_solicitudes_mod', ['status'], unique=False)
    op.create_index(op.f('ix_sigarh_roles_turno_solicitudes_mod_tenant_id'), 'sigarh_roles_turno_solicitudes_mod', ['tenant_id'], unique=False)
    op.create_table('sigarh_roles_turno_actividades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rol_empleado_id', sa.UUID(), nullable=False),
    sa.Column('actividad_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['sigarh_actividades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_empleado_id'], ['sigarh_roles_turno_empleados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_roles_turno_actividades_rol_empleado_id'), 'sigarh_roles_turno_actividades', ['rol_empleado_id'], unique=False)
    op.create_table('sigarh_roles_turno_turnos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rol_actividad_id', sa.UUID(), nullable=False),
    sa.Column('horario_guardia_id', sa.UUID(), nullable=True),
    sa.Column('dias_semana', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horario_guardia_id'], ['sigarh_horarios_guardia.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rol_actividad_id'], ['sigarh_roles_turno_actividades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_roles_turno_turnos_rol_actividad_id'), 'sigarh_roles_turno_turnos', ['rol_actividad_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sigarh_roles_turno_turnos_rol_actividad_id'), table_name='sigarh_roles_turno_turnos')
    op.drop_table('sigarh_roles_turno_turnos')
    op.drop_index(op.f('ix_sigarh_roles_turno_actividades_rol_empleado_id'), table_name='sigarh_roles_turno_actividades')
    op.drop_table('sigarh_roles_turno_actividades')
    op.drop_index(op.f('ix_sigarh_roles_turno_solicitudes_mod_tenant_id'), table_name='sigarh_roles_turno_solicitudes_mod')
    op.drop_index(op.f('ix_sigarh_roles_turno_solicitudes_mod_status'), table_name='sigarh_roles_turno_solicitudes_mod')
    op.drop_index(op.f('ix_sigarh_roles_turno_solicitudes_mod_rol_id'), table_name='sigarh_roles_turno_solicitudes_mod')
    op.drop_table('sigarh_roles_turno_solicitudes_mod')
    op.drop_index(op.f('ix_sigarh_roles_turno_empleados_rol_id'), table_name='sigarh_roles_turno_empleados')
    op.drop_table('sigarh_roles_turno_empleados')
    op.drop_index(op.f('ix_sigarh_roles_turno_tipo_rol'), table_name='sigarh_roles_turno')
    op.drop_index(op.f('ix_sigarh_roles_turno_tenant_id'), table_name='sigarh_roles_turno')
    op.drop_index(op.f('ix_sigarh_roles_turno_status'), table_name='sigarh_roles_turno')
    op.drop_index(op.f('ix_sigarh_roles_turno_categoria_personal'), table_name='sigarh_roles_turno')
    op.drop_index(op.f('ix_sigarh_roles_turno_anio'), table_name='sigarh_roles_turno')
    op.drop_table('sigarh_roles_turno')
    # ### end Alembic commands ###
