"""add tipo_guardia_id to horario_guardia

Revision ID: 03eab3dfc957
Revises: 7f27f75ed6b3
Create Date: 2026-09-07 10:50:23.711066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03eab3dfc957'
down_revision: Union[str, Sequence[str], None] = '7f27f75ed6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sigarh_horarios_guardia', sa.Column('tipo_guardia_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sigarh_horarios_guardia', 'sigarh_tipos_guardia', ['tipo_guardia_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sigarh_horarios_guardia', type_='foreignkey')
    op.drop_column('sigarh_horarios_guardia', 'tipo_guardia_id')
    # ### end Alembic commands ###
