"""crear tablas sigarh config farmacia

Revision ID: 04e01279b70c
Revises: 0fed3779f7f3
Create Date: 2026-09-03 16:13:37.368890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e01279b70c'
down_revision: Union[str, Sequence[str], None] = '0fed3779f7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_almacenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fuente_financiamiento', sa.String(length=100), nullable=True),
    sa.Column('ubicacion_fisica', sa.Text(), nullable=True),
    sa.Column('despacha_recetas', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_almacenes_tenant_id'), 'sigarh_almacenes', ['tenant_id'], unique=False)
    op.create_table('sigarh_medicamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=255), nullable=False),
    sa.Column('dci', sa.String(length=255), nullable=True),
    sa.Column('nombre_generico', sa.String(length=255), nullable=True),
    sa.Column('presentacion', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('concentracion', sa.String(length=100), nullable=True),
    sa.Column('forma_farmaceutica', sa.String(length=100), nullable=True),
    sa.Column('via_administracion', sa.String(length=100), nullable=True),
    sa.Column('codigo_atc', sa.String(length=50), nullable=True),
    sa.Column('numero_registro_sanitario', sa.String(length=100), nullable=True),
    sa.Column('laboratorio_fabricante', sa.String(length=255), nullable=True),
    sa.Column('pais_origen', sa.String(length=100), nullable=True),
    sa.Column('condicion_venta', sa.String(length=50), nullable=True),
    sa.Column('tipo_producto_id', sa.UUID(), nullable=True),
    sa.Column('precio_referencia', sa.Float(), nullable=True),
    sa.Column('requiere_receta', sa.Boolean(), nullable=False),
    sa.Column('controlado', sa.Boolean(), nullable=False),
    sa.Column('fiscalizado_digemid', sa.Boolean(), nullable=False),
    sa.Column('reporte_sismed', sa.Boolean(), nullable=False),
    sa.Column('stock_minimo_alerta', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requiere_cadena_frio', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_medicamentos_tenant_id'), 'sigarh_medicamentos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sigarh_medicamentos_tenant_id'), table_name='sigarh_medicamentos')
    op.drop_table('sigarh_medicamentos')
    op.drop_index(op.f('ix_sigarh_almacenes_tenant_id'), table_name='sigarh_almacenes')
    op.drop_table('sigarh_almacenes')
    # ### end Alembic commands ###
