"""add triaje

Revision ID: 0800678b4da5
Revises: bbe1987cc137
Create Date: 2026-09-06 18:44:16.062541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0800678b4da5'
down_revision: Union[str, Sequence[str], None] = 'bbe1987cc137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('triajes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cita_id', sa.UUID(), nullable=False),
    sa.Column('realizado_por_id', sa.UUID(), nullable=True),
    sa.Column('pulso', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('presion_sistolica', sa.Integer(), nullable=True),
    sa.Column('presion_diastolica', sa.Integer(), nullable=True),
    sa.Column('frecuencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frecuencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('talla', sa.Float(), nullable=True),
    sa.Column('perimetro_abdominal', sa.Float(), nullable=True),
    sa.Column('perimetro_cefalico', sa.Float(), nullable=True),
    sa.Column('saturacion_o2', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['realizado_por_id'], ['sigarh_empleados.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cita_id')
    )
    op.create_index(op.f('ix_triajes_tenant_id'), 'triajes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triajes_tenant_id'), table_name='triajes')
    op.drop_table('triajes')
    # ### end Alembic commands ###
