"""crear tablas sigarh movimientos

Revision ID: 0ade2c30aedb
Revises: cf095ca1b506
Create Date: 2026-09-03 15:56:16.798044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ade2c30aedb'
down_revision: Union[str, Sequence[str], None] = 'cf095ca1b506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_cambios_turno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('servicio_id', sa.UUID(), nullable=True),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('solicitante_id', sa.UUID(), nullable=False),
    sa.Column('fecha_original', sa.Date(), nullable=False),
    sa.Column('modalidad_solicitante', sa.String(length=100), nullable=True),
    sa.Column('aceptante_id', sa.UUID(), nullable=True),
    sa.Column('fecha_reemplazo', sa.Date(), nullable=False),
    sa.Column('modalidad_aceptante', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aceptante_id'], ['sigarh_empleados.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['sigarh_servicios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solicitante_id'], ['sigarh_empleados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_cambios_turno_tenant_id'), 'sigarh_cambios_turno', ['tenant_id'], unique=False)
    op.create_table('sigarh_licencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('motivo_id', sa.UUID(), nullable=True),
    sa.Column('fecha_tramite', sa.Date(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.Column('documento_url', sa.Text(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['sigarh_empleados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motivo_id'], ['sigarh_motivos_justificacion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_licencias_tenant_id'), 'sigarh_licencias', ['tenant_id'], unique=False)
    op.create_table('sigarh_papeletas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('motivo_id', sa.UUID(), nullable=True),
    sa.Column('fecha_tramite', sa.Date(), nullable=False),
    sa.Column('documento_url', sa.Text(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('mes_actual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['sigarh_empleados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motivo_id'], ['sigarh_motivos_justificacion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_papeletas_tenant_id'), 'sigarh_papeletas', ['tenant_id'], unique=False)
    op.create_table('sigarh_vacaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('motivo_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('documento_url', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('mes_actual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['sigarh_empleados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motivo_id'], ['sigarh_motivos_justificacion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_vacaciones_tenant_id'), 'sigarh_vacaciones', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sigarh_vacaciones_tenant_id'), table_name='sigarh_vacaciones')
    op.drop_table('sigarh_vacaciones')
    op.drop_index(op.f('ix_sigarh_papeletas_tenant_id'), table_name='sigarh_papeletas')
    op.drop_table('sigarh_papeletas')
    op.drop_index(op.f('ix_sigarh_licencias_tenant_id'), table_name='sigarh_licencias')
    op.drop_table('sigarh_licencias')
    op.drop_index(op.f('ix_sigarh_cambios_turno_tenant_id'), table_name='sigarh_cambios_turno')
    op.drop_table('sigarh_cambios_turno')
    # ### end Alembic commands ###
