"""crear tablas sigarh infraestructura hosp

Revision ID: 0fed3779f7f3
Revises: d6a49170b21b
Create Date: 2026-09-03 16:05:04.180660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fed3779f7f3'
down_revision: Union[str, Sequence[str], None] = 'd6a49170b21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_pisos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_pisos_tenant_id'), 'sigarh_pisos', ['tenant_id'], unique=False)
    op.create_table('sigarh_salas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('piso_id', sa.UUID(), nullable=True),
    sa.Column('servicio_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['piso_id'], ['sigarh_pisos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['sigarh_servicios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_salas_tenant_id'), 'sigarh_salas', ['tenant_id'], unique=False)
    op.create_table('sigarh_camas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sala_id', sa.UUID(), nullable=True),
    sa.Column('piso_id', sa.UUID(), nullable=True),
    sa.Column('servicio_id', sa.UUID(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('sala_texto', sa.String(length=255), nullable=True),
    sa.Column('piso_texto', sa.String(length=255), nullable=True),
    sa.Column('servicio_texto', sa.String(length=255), nullable=True),
    sa.Column('tipo_cama', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['piso_id'], ['sigarh_pisos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sala_id'], ['sigarh_salas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['sigarh_servicios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_camas_tenant_id'), 'sigarh_camas', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sigarh_camas_tenant_id'), table_name='sigarh_camas')
    op.drop_table('sigarh_camas')
    op.drop_index(op.f('ix_sigarh_salas_tenant_id'), table_name='sigarh_salas')
    op.drop_table('sigarh_salas')
    op.drop_index(op.f('ix_sigarh_pisos_tenant_id'), table_name='sigarh_pisos')
    op.drop_table('sigarh_pisos')
    # ### end Alembic commands ###
