"""crear tablas sigarh imagenologia laboratorio

Revision ID: 15bf772826d7
Revises: f5a3c3eee53f
Create Date: 2026-09-03 16:22:29.245100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bf772826d7'
down_revision: Union[str, Sequence[str], None] = 'f5a3c3eee53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_examenes_imagenologia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('modalidad', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('parte_cuerpo', sa.String(length=100), nullable=True),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('requiere_contraste', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_examenes_imagenologia_tenant_id'), 'sigarh_examenes_imagenologia', ['tenant_id'], unique=False)
    op.create_table('sigarh_examenes_laboratorio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('tipo_muestra', sa.String(length=100), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.Column('tiempo_resultado_horas', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('valores_referencia', sa.Text(), nullable=True),
    sa.Column('requiere_ayuno', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_examenes_laboratorio_tenant_id'), 'sigarh_examenes_laboratorio', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sigarh_examenes_laboratorio_tenant_id'), table_name='sigarh_examenes_laboratorio')
    op.drop_table('sigarh_examenes_laboratorio')
    op.drop_index(op.f('ix_sigarh_examenes_imagenologia_tenant_id'), table_name='sigarh_examenes_imagenologia')
    op.drop_table('sigarh_examenes_imagenologia')
    # ### end Alembic commands ###
