"""add atencion medica

Revision ID: 30a09d217780
Revises: 0800678b4da5
Create Date: 2026-09-06 20:01:16.643517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a09d217780'
down_revision: Union[str, Sequence[str], None] = '0800678b4da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atenciones_medicas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cita_id', sa.UUID(), nullable=False),
    sa.Column('motivo_consulta', sa.Text(), nullable=False),
    sa.Column('examen_clinico', sa.Text(), nullable=True),
    sa.Column('plan_tratamiento', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('destino_atencion', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('firmado_por_id', sa.UUID(), nullable=True),
    sa.Column('firmado_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firmado_por_id'], ['sigarh_empleados.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cita_id')
    )
    op.create_index(op.f('ix_atenciones_medicas_tenant_id'), 'atenciones_medicas', ['tenant_id'], unique=False)
    op.create_table('atencion_diagnosticos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('atencion_medica_id', sa.UUID(), nullable=False),
    sa.Column('diagnostico_cie10_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atencion_medica_id'], ['atenciones_medicas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnostico_cie10_id'], ['sigarh_diagnosticos_cie10.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atencion_diagnosticos')
    op.drop_index(op.f('ix_atenciones_medicas_tenant_id'), table_name='atenciones_medicas')
    op.drop_table('atenciones_medicas')
    # ### end Alembic commands ###
