"""add ubigeo catalog and patient fields

Revision ID: 387d44c7808d
Revises: 6e49c8636a4d
Create Date: 2026-09-06 14:43:37.034013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387d44c7808d'
down_revision: Union[str, Sequence[str], None] = '6e49c8636a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ubigeo_departamentos',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubigeo_provincias',
    sa.Column('id', sa.String(length=4), nullable=False),
    sa.Column('departamento_id', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['ubigeo_departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubigeo_distritos',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('provincia_id', sa.String(length=4), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['provincia_id'], ['ubigeo_provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('patients', sa.Column('document_type', sa.String(length=20), nullable=False))
    op.add_column('patients', sa.Column('is_nn', sa.Boolean(), nullable=False))
    op.add_column('patients', sa.Column('second_name', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('marital_status', sa.String(length=30), nullable=True))
    op.add_column('patients', sa.Column('education_level', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('ethnicity', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('phone_is_whatsapp', sa.Boolean(), nullable=False))
    op.add_column('patients', sa.Column('populated_center', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('country', sa.String(length=50), nullable=False))
    op.add_column('patients', sa.Column('birth_same_as_address', sa.Boolean(), nullable=False))
    op.add_column('patients', sa.Column('birth_department_id', sa.String(length=2), nullable=True))
    op.add_column('patients', sa.Column('birth_province_id', sa.String(length=4), nullable=True))
    op.add_column('patients', sa.Column('birth_district_id', sa.String(length=6), nullable=True))
    op.add_column('patients', sa.Column('birth_populated_center', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('birth_country', sa.String(length=50), nullable=False))
    op.alter_column('patients', 'dni',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=15),
               nullable=True)
    op.drop_index(op.f('ix_patients_dni'), table_name='patients')
    op.drop_index(op.f('ix_patients_tenant_id_dni'), table_name='patients')
    op.create_unique_constraint('ix_patients_tenant_id_dni', 'patients', ['tenant_id', 'dni'])
    op.create_foreign_key(None, 'patients', 'ubigeo_departamentos', ['department_id'], ['id'])
    op.create_foreign_key(None, 'patients', 'ubigeo_departamentos', ['birth_department_id'], ['id'])
    op.create_foreign_key(None, 'patients', 'ubigeo_provincias', ['birth_province_id'], ['id'])
    op.create_foreign_key(None, 'patients', 'ubigeo_provincias', ['province_id'], ['id'])
    op.create_foreign_key(None, 'patients', 'ubigeo_distritos', ['birth_district_id'], ['id'])
    op.create_foreign_key(None, 'patients', 'ubigeo_distritos', ['district_id'], ['id'])
    op.drop_index(op.f('ix_sigarh_roles_sistema_tenant_codigo'), table_name='sigarh_roles_sistema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sigarh_roles_sistema_tenant_codigo'), 'sigarh_roles_sistema', ['tenant_id', 'codigo'], unique=True)
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint('ix_patients_tenant_id_dni', 'patients', type_='unique')
    op.create_index(op.f('ix_patients_tenant_id_dni'), 'patients', ['tenant_id', 'dni'], unique=True)
    op.create_index(op.f('ix_patients_dni'), 'patients', ['dni'], unique=False)
    op.alter_column('patients', 'dni',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=8),
               nullable=False)
    op.drop_column('patients', 'birth_country')
    op.drop_column('patients', 'birth_populated_center')
    op.drop_column('patients', 'birth_district_id')
    op.drop_column('patients', 'birth_province_id')
    op.drop_column('patients', 'birth_department_id')
    op.drop_column('patients', 'birth_same_as_address')
    op.drop_column('patients', 'country')
    op.drop_column('patients', 'populated_center')
    op.drop_column('patients', 'phone_is_whatsapp')
    op.drop_column('patients', 'language')
    op.drop_column('patients', 'ethnicity')
    op.drop_column('patients', 'occupation')
    op.drop_column('patients', 'education_level')
    op.drop_column('patients', 'marital_status')
    op.drop_column('patients', 'second_name')
    op.drop_column('patients', 'is_nn')
    op.drop_column('patients', 'document_type')
    op.drop_table('ubigeo_distritos')
    op.drop_table('ubigeo_provincias')
    op.drop_table('ubigeo_departamentos')
    # ### end Alembic commands ###
