"""add requiere_consultorio to actividad

Revision ID: 3a8179f5d285
Revises: 03eab3dfc957
Create Date: 2026-09-07 11:51:33.275970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a8179f5d285'
down_revision: Union[str, Sequence[str], None] = '03eab3dfc957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sigarh_actividades', sa.Column('requiere_consultorio', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sigarh_actividades', 'requiere_consultorio')
    # ### end Alembic commands ###
