"""rrhh: asistencia y tolerancias completas, especialidad descripcion, justificacion tramite

Revision ID: 3df7fd60dc0a
Revises: 015c1d94ffb7
Create Date: 2026-09-09 09:06:55.100344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df7fd60dc0a'
down_revision: Union[str, Sequence[str], None] = '015c1d94ffb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sigarh_especialidades', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('sigarh_justificaciones', sa.Column('numero_documento', sa.String(length=50), nullable=True))
    op.add_column('sigarh_justificaciones', sa.Column('fecha_tramite', sa.Date(), nullable=True))
    op.add_column('sigarh_registro_asistencia', sa.Column('grupo_ocupacional_id', sa.UUID(), nullable=True))
    op.add_column('sigarh_registro_asistencia', sa.Column('horario_guardia_id', sa.UUID(), nullable=True))
    op.add_column('sigarh_registro_asistencia', sa.Column('actividad_texto', sa.String(length=100), nullable=True))
    op.add_column('sigarh_registro_asistencia', sa.Column('servicio_texto', sa.String(length=100), nullable=True))
    op.add_column('sigarh_registro_asistencia', sa.Column('hora_entrada_programada', sa.String(length=5), nullable=True))
    op.add_column('sigarh_registro_asistencia', sa.Column('hora_salida_programada', sa.String(length=5), nullable=True))
    op.add_column('sigarh_registro_asistencia', sa.Column('hora_entrada_real', sa.String(length=5), nullable=True))
    op.add_column('sigarh_registro_asistencia', sa.Column('hora_salida_real', sa.String(length=5), nullable=True))
    # Las tablas pueden contener registros previos. Se usa un default temporal
    # para que PostgreSQL pueda crear las columnas NOT NULL sin perder datos.
    op.add_column('sigarh_registro_asistencia', sa.Column(
        'minutos_tardanza', sa.Integer(), nullable=False, server_default=sa.text('0')
    ))
    op.add_column('sigarh_registro_asistencia', sa.Column('registrado_por', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'sigarh_registro_asistencia', 'sigarh_grupos_ocupacionales', ['grupo_ocupacional_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sigarh_registro_asistencia', 'sigarh_horarios_guardia', ['horario_guardia_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sigarh_registro_asistencia', 'hora_entrada')
    op.drop_column('sigarh_registro_asistencia', 'hora_salida')
    op.add_column('sigarh_tolerancias', sa.Column('dependencia_id', sa.UUID(), nullable=True))
    op.add_column('sigarh_tolerancias', sa.Column('grupo_ocupacional_id', sa.UUID(), nullable=True))
    op.add_column('sigarh_tolerancias', sa.Column(
        'minutos_tolerancia', sa.Integer(), nullable=False, server_default=sa.text('0')
    ))
    op.add_column('sigarh_tolerancias', sa.Column(
        'minutos_tolerancia_dia', sa.Integer(), nullable=False, server_default=sa.text('0')
    ))
    op.alter_column('sigarh_tolerancias', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'sigarh_tolerancias', 'sigarh_grupos_ocupacionales', ['grupo_ocupacional_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sigarh_tolerancias', 'sigarh_dependencias', ['dependencia_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sigarh_tolerancias', 'minutos_entrada')
    op.drop_column('sigarh_tolerancias', 'descripcion')
    op.drop_column('sigarh_tolerancias', 'minutos_salida')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sigarh_tolerancias', sa.Column('minutos_salida', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sigarh_tolerancias', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sigarh_tolerancias', sa.Column('minutos_entrada', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sigarh_tolerancias', type_='foreignkey')
    op.drop_constraint(None, 'sigarh_tolerancias', type_='foreignkey')
    op.alter_column('sigarh_tolerancias', 'nombre',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('sigarh_tolerancias', 'minutos_tolerancia_dia')
    op.drop_column('sigarh_tolerancias', 'minutos_tolerancia')
    op.drop_column('sigarh_tolerancias', 'grupo_ocupacional_id')
    op.drop_column('sigarh_tolerancias', 'dependencia_id')
    op.add_column('sigarh_registro_asistencia', sa.Column('hora_salida', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('sigarh_registro_asistencia', sa.Column('hora_entrada', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sigarh_registro_asistencia', type_='foreignkey')
    op.drop_constraint(None, 'sigarh_registro_asistencia', type_='foreignkey')
    op.drop_column('sigarh_registro_asistencia', 'registrado_por')
    op.drop_column('sigarh_registro_asistencia', 'minutos_tardanza')
    op.drop_column('sigarh_registro_asistencia', 'hora_salida_real')
    op.drop_column('sigarh_registro_asistencia', 'hora_entrada_real')
    op.drop_column('sigarh_registro_asistencia', 'hora_salida_programada')
    op.drop_column('sigarh_registro_asistencia', 'hora_entrada_programada')
    op.drop_column('sigarh_registro_asistencia', 'servicio_texto')
    op.drop_column('sigarh_registro_asistencia', 'actividad_texto')
    op.drop_column('sigarh_registro_asistencia', 'horario_guardia_id')
    op.drop_column('sigarh_registro_asistencia', 'grupo_ocupacional_id')
    op.drop_column('sigarh_justificaciones', 'fecha_tramite')
    op.drop_column('sigarh_justificaciones', 'numero_documento')
    op.drop_column('sigarh_especialidades', 'descripcion')
    # ### end Alembic commands ###
