"""add referencia

Revision ID: 428bfcb15e01
Revises: 65c75788a950
Create Date: 2026-09-07 16:27:54.263696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428bfcb15e01'
down_revision: Union[str, Sequence[str], None] = '65c75788a950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('atencion_medica_id', sa.UUID(), nullable=False),
    sa.Column('codigo_renipress_destino', sa.String(length=20), nullable=True),
    sa.Column('nombre_ipress_destino', sa.String(length=255), nullable=True),
    sa.Column('tenant_destino_id', sa.UUID(), nullable=True),
    sa.Column('especialidad_destino', sa.String(length=150), nullable=True),
    sa.Column('diagnostico_id', sa.UUID(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('numero_referencia', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atencion_medica_id'], ['atenciones_medicas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnostico_id'], ['sigarh_diagnosticos_cie10.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_destino_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atencion_medica_id'),
    sa.UniqueConstraint('numero_referencia')
    )
    op.create_index(op.f('ix_referencias_tenant_id'), 'referencias', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referencias_tenant_id'), table_name='referencias')
    op.drop_table('referencias')
    # ### end Alembic commands ###
