"""add indicaciones alta

Revision ID: 56d11705a3ba
Revises: e268d127e63d
Create Date: 2026-09-06 22:40:04.960197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d11705a3ba'
down_revision: Union[str, Sequence[str], None] = 'e268d127e63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atenciones_medicas', sa.Column('indicaciones_alta', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('atenciones_medicas', 'indicaciones_alta')
    # ### end Alembic commands ###
