"""update dependencia fields

Revision ID: 5752506da23f
Revises: f378f23755f9
Create Date: 2026-09-07 10:20:17.064240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5752506da23f'
down_revision: Union[str, Sequence[str], None] = 'f378f23755f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sigarh_dependencias', sa.Column('clasificacion', sa.String(length=50), nullable=False))
    op.add_column('sigarh_dependencias', sa.Column('departamento_id', sa.UUID(), nullable=True))
    op.add_column('sigarh_dependencias', sa.Column('servicio_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sigarh_dependencias', 'sigarh_servicios', ['servicio_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sigarh_dependencias', 'sigarh_departamentos', ['departamento_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sigarh_dependencias', 'descripcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sigarh_dependencias', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sigarh_dependencias', type_='foreignkey')
    op.drop_constraint(None, 'sigarh_dependencias', type_='foreignkey')
    op.drop_column('sigarh_dependencias', 'servicio_id')
    op.drop_column('sigarh_dependencias', 'departamento_id')
    op.drop_column('sigarh_dependencias', 'clasificacion')
    # ### end Alembic commands ###
