"""add orden imagen and interconsulta

Revision ID: 65c75788a950
Revises: c54d8211ada0
Create Date: 2026-09-07 15:55:32.211194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c75788a950'
down_revision: Union[str, Sequence[str], None] = 'c54d8211ada0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interconsultas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('atencion_medica_id', sa.UUID(), nullable=False),
    sa.Column('especialidad_destino_id', sa.UUID(), nullable=False),
    sa.Column('diagnostico_id', sa.UUID(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('urgente', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cita_generada_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atencion_medica_id'], ['atenciones_medicas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cita_generada_id'], ['citas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['diagnostico_id'], ['sigarh_diagnosticos_cie10.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['especialidad_destino_id'], ['sigarh_especialidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atencion_medica_id')
    )
    op.create_index(op.f('ix_interconsultas_tenant_id'), 'interconsultas', ['tenant_id'], unique=False)
    op.create_table('ordenes_imagen',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('atencion_medica_id', sa.UUID(), nullable=False),
    sa.Column('numero_orden', sa.String(length=30), nullable=False),
    sa.Column('indicacion_clinica', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atencion_medica_id'], ['atenciones_medicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atencion_medica_id'),
    sa.UniqueConstraint('numero_orden')
    )
    op.create_index(op.f('ix_ordenes_imagen_tenant_id'), 'ordenes_imagen', ['tenant_id'], unique=False)
    op.create_table('orden_imagen_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orden_id', sa.UUID(), nullable=False),
    sa.Column('examen_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examen_id'], ['sigarh_examenes_imagenologia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_imagen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden_imagen_items')
    op.drop_index(op.f('ix_ordenes_imagen_tenant_id'), table_name='ordenes_imagen')
    op.drop_table('ordenes_imagen')
    op.drop_index(op.f('ix_interconsultas_tenant_id'), table_name='interconsultas')
    op.drop_table('interconsultas')
    # ### end Alembic commands ###
