"""crear tablas sigarh mantenimiento

Revision ID: 7001a63f5cfb
Revises: ad73a93d5ba1
Create Date: 2026-09-02 16:46:52.105315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7001a63f5cfb'
down_revision: Union[str, Sequence[str], None] = 'ad73a93d5ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_departamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_departamentos_tenant_id'), 'sigarh_departamentos', ['tenant_id'], unique=False)
    op.create_table('sigarh_grupos_ocupacionales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_grupos_ocupacionales_tenant_id'), 'sigarh_grupos_ocupacionales', ['tenant_id'], unique=False)
    op.create_table('sigarh_horarios_guardia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('hora_fin', sa.String(length=5), nullable=False),
    sa.Column('horas_totales', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_horarios_guardia_tenant_id'), 'sigarh_horarios_guardia', ['tenant_id'], unique=False)
    op.create_table('sigarh_niveles_remunerativos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_niveles_remunerativos_tenant_id'), 'sigarh_niveles_remunerativos', ['tenant_id'], unique=False)
    op.create_table('sigarh_roles_sistema',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_roles_sistema_tenant_id'), 'sigarh_roles_sistema', ['tenant_id'], unique=False)
    op.create_table('sigarh_tipos_actividad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_tipos_actividad_tenant_id'), 'sigarh_tipos_actividad', ['tenant_id'], unique=False)
    op.create_table('sigarh_tipos_guardia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('horas', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_tipos_guardia_tenant_id'), 'sigarh_tipos_guardia', ['tenant_id'], unique=False)
    op.create_table('sigarh_tipos_trabajador',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_tipos_trabajador_tenant_id'), 'sigarh_tipos_trabajador', ['tenant_id'], unique=False)
    op.create_table('sigarh_actividades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo_actividad_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_actividad_id'], ['sigarh_tipos_actividad.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_actividades_tenant_id'), 'sigarh_actividades', ['tenant_id'], unique=False)
    op.create_table('sigarh_guardias_valorizadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo_guardia_id', sa.UUID(), nullable=True),
    sa.Column('grupo_ocupacional_id', sa.UUID(), nullable=True),
    sa.Column('nivel_remunerativo_id', sa.UUID(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_ocupacional_id'], ['sigarh_grupos_ocupacionales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nivel_remunerativo_id'], ['sigarh_niveles_remunerativos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_guardia_id'], ['sigarh_tipos_guardia.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_guardias_valorizadas_tenant_id'), 'sigarh_guardias_valorizadas', ['tenant_id'], unique=False)
    op.create_table('sigarh_perfiles_usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('rol_sistema_id', sa.UUID(), nullable=True),
    sa.Column('modulos_acceso', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rol_sistema_id'], ['sigarh_roles_sistema.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_perfiles_usuario_tenant_id'), 'sigarh_perfiles_usuario', ['tenant_id'], unique=False)
    op.create_table('sigarh_servicios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('departamento_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['sigarh_departamentos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_servicios_tenant_id'), 'sigarh_servicios', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sigarh_servicios_tenant_id'), table_name='sigarh_servicios')
    op.drop_table('sigarh_servicios')
    op.drop_index(op.f('ix_sigarh_perfiles_usuario_tenant_id'), table_name='sigarh_perfiles_usuario')
    op.drop_table('sigarh_perfiles_usuario')
    op.drop_index(op.f('ix_sigarh_guardias_valorizadas_tenant_id'), table_name='sigarh_guardias_valorizadas')
    op.drop_table('sigarh_guardias_valorizadas')
    op.drop_index(op.f('ix_sigarh_actividades_tenant_id'), table_name='sigarh_actividades')
    op.drop_table('sigarh_actividades')
    op.drop_index(op.f('ix_sigarh_tipos_trabajador_tenant_id'), table_name='sigarh_tipos_trabajador')
    op.drop_table('sigarh_tipos_trabajador')
    op.drop_index(op.f('ix_sigarh_tipos_guardia_tenant_id'), table_name='sigarh_tipos_guardia')
    op.drop_table('sigarh_tipos_guardia')
    op.drop_index(op.f('ix_sigarh_tipos_actividad_tenant_id'), table_name='sigarh_tipos_actividad')
    op.drop_table('sigarh_tipos_actividad')
    op.drop_index(op.f('ix_sigarh_roles_sistema_tenant_id'), table_name='sigarh_roles_sistema')
    op.drop_table('sigarh_roles_sistema')
    op.drop_index(op.f('ix_sigarh_niveles_remunerativos_tenant_id'), table_name='sigarh_niveles_remunerativos')
    op.drop_table('sigarh_niveles_remunerativos')
    op.drop_index(op.f('ix_sigarh_horarios_guardia_tenant_id'), table_name='sigarh_horarios_guardia')
    op.drop_table('sigarh_horarios_guardia')
    op.drop_index(op.f('ix_sigarh_grupos_ocupacionales_tenant_id'), table_name='sigarh_grupos_ocupacionales')
    op.drop_table('sigarh_grupos_ocupacionales')
    op.drop_index(op.f('ix_sigarh_departamentos_tenant_id'), table_name='sigarh_departamentos')
    op.drop_table('sigarh_departamentos')
    # ### end Alembic commands ###
