"""add tipo_grupo_ocupacional and tipo_grupo_id to grupo_ocupacional

Revision ID: 7bbc7df736cd
Revises: 3a8179f5d285
Create Date: 2026-09-07 12:10:00.030136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbc7df736cd'
down_revision: Union[str, Sequence[str], None] = '3a8179f5d285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_tipos_grupo_ocupacional',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_tipos_grupo_ocupacional_tenant_id'), 'sigarh_tipos_grupo_ocupacional', ['tenant_id'], unique=False)
    op.add_column('sigarh_grupos_ocupacionales', sa.Column('tipo_grupo_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sigarh_grupos_ocupacionales', 'sigarh_tipos_grupo_ocupacional', ['tipo_grupo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sigarh_grupos_ocupacionales', type_='foreignkey')
    op.drop_column('sigarh_grupos_ocupacionales', 'tipo_grupo_id')
    op.drop_index(op.f('ix_sigarh_tipos_grupo_ocupacional_tenant_id'), table_name='sigarh_tipos_grupo_ocupacional')
    op.drop_table('sigarh_tipos_grupo_ocupacional')
    # ### end Alembic commands ###
