"""caja sesiones y cobros

Revision ID: 7c2d914ef8a3
Revises: a91d47c30b5e
Create Date: 2026-09-14 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c2d914ef8a3'
down_revision: Union[str, Sequence[str], None] = 'a91d47c30b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caja_correlativos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'tipo')
    )
    op.create_table('caja_sesiones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('caja_id', sa.UUID(), nullable=False),
    sa.Column('cajero_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('monto_apertura', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('observaciones_apertura', sa.Text(), nullable=True),
    sa.Column('monto_cierre_declarado', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('monto_cierre_sistema', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('observaciones_cierre', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('abierta_at', sa.DateTime(), nullable=False),
    sa.Column('cerrada_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caja_id'], ['sigarh_cajas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cajero_id'], ['sigarh_empleados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero')
    )
    op.create_index(op.f('ix_caja_sesiones_caja_id'), 'caja_sesiones', ['caja_id'], unique=False)
    op.create_index(op.f('ix_caja_sesiones_tenant_id'), 'caja_sesiones', ['tenant_id'], unique=False)
    op.create_index('ux_caja_sesion_abierta', 'caja_sesiones', ['caja_id'], unique=True,
        postgresql_where=sa.text("estado = 'abierta'"))
    op.create_table('caja_cobros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('caja_sesion_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('forma_pago', sa.String(length=20), nullable=False),
    sa.Column('fuente_financiamiento', sa.String(length=100), nullable=True),
    sa.Column('monto', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('monto > 0'),
    sa.ForeignKeyConstraint(['caja_sesion_id'], ['caja_sesiones.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'numero')
    )
    op.create_index(op.f('ix_caja_cobros_caja_sesion_id'), 'caja_cobros', ['caja_sesion_id'], unique=False)
    op.create_index(op.f('ix_caja_cobros_created_at'), 'caja_cobros', ['created_at'], unique=False)
    op.create_index(op.f('ix_caja_cobros_numero_cuenta'), 'caja_cobros', ['numero_cuenta'], unique=False)
    op.create_index(op.f('ix_caja_cobros_tenant_id'), 'caja_cobros', ['tenant_id'], unique=False)
    op.create_table('caja_cobro_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cobro_id', sa.UUID(), nullable=False),
    sa.Column('origen', sa.String(length=30), nullable=False),
    sa.Column('origen_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.CheckConstraint('monto > 0'),
    sa.ForeignKeyConstraint(['cobro_id'], ['caja_cobros.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caja_cobro_items_cobro_id'), 'caja_cobro_items', ['cobro_id'], unique=False)
    op.create_index(op.f('ix_caja_cobro_items_origen_id'), 'caja_cobro_items', ['origen_id'], unique=False)
    op.create_index(op.f('ix_caja_cobro_items_tenant_id'), 'caja_cobro_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_caja_cobro_items_tenant_id'), table_name='caja_cobro_items')
    op.drop_index(op.f('ix_caja_cobro_items_origen_id'), table_name='caja_cobro_items')
    op.drop_index(op.f('ix_caja_cobro_items_cobro_id'), table_name='caja_cobro_items')
    op.drop_table('caja_cobro_items')
    op.drop_index(op.f('ix_caja_cobros_tenant_id'), table_name='caja_cobros')
    op.drop_index(op.f('ix_caja_cobros_numero_cuenta'), table_name='caja_cobros')
    op.drop_index(op.f('ix_caja_cobros_created_at'), table_name='caja_cobros')
    op.drop_index(op.f('ix_caja_cobros_caja_sesion_id'), table_name='caja_cobros')
    op.drop_table('caja_cobros')
    op.drop_index('ux_caja_sesion_abierta', table_name='caja_sesiones')
    op.drop_index(op.f('ix_caja_sesiones_tenant_id'), table_name='caja_sesiones')
    op.drop_index(op.f('ix_caja_sesiones_caja_id'), table_name='caja_sesiones')
    op.drop_table('caja_sesiones')
    op.drop_table('caja_correlativos')
    # ### end Alembic commands ###
