"""add es_laborable and requiere_epp to tipo_guardia

Revision ID: 7f27f75ed6b3
Revises: 5752506da23f
Create Date: 2026-09-07 10:35:31.294349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f27f75ed6b3'
down_revision: Union[str, Sequence[str], None] = '5752506da23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sigarh_tipos_guardia', sa.Column('es_laborable', sa.Boolean(), nullable=False))
    op.add_column('sigarh_tipos_guardia', sa.Column('requiere_epp', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sigarh_tipos_guardia', 'requiere_epp')
    op.drop_column('sigarh_tipos_guardia', 'es_laborable')
    # ### end Alembic commands ###
