"""add programacion medica

Revision ID: 8aeea41cba23
Revises: 387d44c7808d
Create Date: 2026-09-06 16:34:21.062604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aeea41cba23'
down_revision: Union[str, Sequence[str], None] = '387d44c7808d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programaciones_medicas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('medico_id', sa.UUID(), nullable=False),
    sa.Column('especialidad_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('turno', sa.String(length=20), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('hora_fin', sa.String(length=5), nullable=False),
    sa.Column('tiempo_promedio_atencion', sa.Integer(), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=50), nullable=False),
    sa.Column('mostrar_en_consultorio', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['sigarh_especialidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medico_id'], ['sigarh_empleados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programaciones_medicas_tenant_id'), 'programaciones_medicas', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programaciones_medicas_tenant_id'), table_name='programaciones_medicas')
    op.drop_table('programaciones_medicas')
    # ### end Alembic commands ###
