"""agregar color a hospital_levels

Revision ID: 92ebb9c0b920
Revises: 18bd16627525
Create Date: 2026-09-02 12:42:37.601822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ebb9c0b920'
down_revision: Union[str, Sequence[str], None] = '18bd16627525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_levels', sa.Column('color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital_levels', 'color')
    # ### end Alembic commands ###
