"""farmacia operativa SISMED

Revision ID: a91f3c2d77e0
Revises: d6ffc75e66ac
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='a91f3c2d77e0'; down_revision='d6ffc75e66ac'; branch_labels=None; depends_on=None
U=postgresql.UUID(as_uuid=True); N=sa.Numeric(14,4)
def upgrade():
    op.create_table('sigarh_proveedores_farmacia',sa.Column('id',U,primary_key=True),sa.Column('tenant_id',U,nullable=False),sa.Column('ruc',sa.String(11),nullable=False),sa.Column('razon_social',sa.String(255),nullable=False),sa.Column('direccion',sa.Text),sa.Column('telefono',sa.String(30)),sa.Column('email',sa.String(255)),sa.Column('registro_digemid',sa.String(100)),sa.Column('is_active',sa.Boolean,nullable=False),sa.Column('created_at',sa.DateTime,nullable=False),sa.UniqueConstraint('tenant_id','ruc'))
    op.create_table('sigarh_catalogos_farmacia',sa.Column('id',U,primary_key=True),sa.Column('tenant_id',U,nullable=False),sa.Column('categoria',sa.String(50),nullable=False),sa.Column('codigo',sa.String(30),nullable=False),sa.Column('nombre',sa.String(150),nullable=False),sa.Column('is_active',sa.Boolean,nullable=False),sa.Column('created_at',sa.DateTime,nullable=False),sa.UniqueConstraint('tenant_id','categoria','codigo'))
    op.create_table('farmacia_correlativos',sa.Column('id',U,primary_key=True),sa.Column('tenant_id',U,nullable=False),sa.Column('tipo',sa.String(30),nullable=False),sa.Column('anio',sa.Integer,nullable=False),sa.Column('ultimo',sa.Integer,nullable=False),sa.UniqueConstraint('tenant_id','tipo','anio'))
    op.create_table('farmacia_lotes',sa.Column('id',U,primary_key=True),sa.Column('tenant_id',U,nullable=False),sa.Column('almacen_id',U,sa.ForeignKey('sigarh_almacenes.id',ondelete='RESTRICT'),nullable=False),sa.Column('medicamento_id',U,sa.ForeignKey('sigarh_medicamentos.id',ondelete='RESTRICT'),nullable=False),sa.Column('numero_lote',sa.String(80),nullable=False),sa.Column('fecha_vencimiento',sa.Date,nullable=False),sa.Column('registro_sanitario',sa.String(100)),sa.Column('stock_actual',N,nullable=False),sa.Column('costo_unitario',N,nullable=False),sa.Column('precio_venta',N,nullable=False),sa.Column('estado',sa.String(20),nullable=False),sa.Column('ubicacion',sa.String(100)),sa.Column('created_at',sa.DateTime,nullable=False),sa.CheckConstraint('stock_actual >= 0'),sa.UniqueConstraint('tenant_id','almacen_id','medicamento_id','numero_lote'))
    op.create_table('farmacia_movimientos',sa.Column('id',U,primary_key=True),sa.Column('tenant_id',U,nullable=False),sa.Column('numero',sa.String(40),nullable=False),sa.Column('tipo',sa.String(10),nullable=False),sa.Column('ambito',sa.String(15),nullable=False),sa.Column('concepto',sa.String(60),nullable=False),sa.Column('almacen_origen_id',U,sa.ForeignKey('sigarh_almacenes.id',ondelete='RESTRICT')),sa.Column('almacen_destino_id',U,sa.ForeignKey('sigarh_almacenes.id',ondelete='RESTRICT')),sa.Column('movimiento_relacionado_id',U,sa.ForeignKey('farmacia_movimientos.id',ondelete='RESTRICT')),sa.Column('patient_id',U,sa.ForeignKey('patients.id',ondelete='RESTRICT')),sa.Column('numero_cuenta',sa.String(40)),sa.Column('fuente_financiamiento',sa.String(80)),sa.Column('tipo_documento',sa.String(40)),sa.Column('numero_documento',sa.String(80)),sa.Column('tipo_documento_origen',sa.String(40)),sa.Column('numero_documento_origen',sa.String(80)),sa.Column('fecha_documento_origen',sa.Date),sa.Column('tipo_proceso',sa.String(50)),sa.Column('numero_proceso',sa.String(80)),sa.Column('tipo_compra',sa.String(50)),sa.Column('proveedor_id',U,sa.ForeignKey('sigarh_proveedores_farmacia.id',ondelete='RESTRICT')),sa.Column('observaciones',sa.Text),sa.Column('total',N,nullable=False),sa.Column('estado',sa.String(20),nullable=False),sa.Column('registrado_por',sa.String(255),nullable=False),sa.Column('confirmado_at',sa.DateTime),sa.Column('motivo_anulacion',sa.Text),sa.Column('created_at',sa.DateTime,nullable=False),sa.UniqueConstraint('tenant_id','numero'))
    op.create_table('farmacia_movimiento_items',sa.Column('id',U,primary_key=True),sa.Column('tenant_id',U,nullable=False),sa.Column('movimiento_id',U,sa.ForeignKey('farmacia_movimientos.id',ondelete='RESTRICT'),nullable=False),sa.Column('medicamento_id',U,sa.ForeignKey('sigarh_medicamentos.id',ondelete='RESTRICT'),nullable=False),sa.Column('lote_id',U,sa.ForeignKey('farmacia_lotes.id',ondelete='RESTRICT')),sa.Column('codigo',sa.String(50),nullable=False),sa.Column('descripcion',sa.String(255),nullable=False),sa.Column('unidad',sa.String(50)),sa.Column('numero_lote',sa.String(80),nullable=False),sa.Column('fecha_vencimiento',sa.Date,nullable=False),sa.Column('registro_sanitario',sa.String(100)),sa.Column('cantidad',N,nullable=False),sa.Column('precio_unitario',N,nullable=False),sa.Column('subtotal',N,nullable=False),sa.CheckConstraint('cantidad > 0'),sa.CheckConstraint('precio_unitario >= 0'))
    op.create_table('farmacia_dispensaciones',sa.Column('id',U,primary_key=True),sa.Column('tenant_id',U,nullable=False),sa.Column('numero',sa.String(40),nullable=False),sa.Column('receta_id',U,sa.ForeignKey('recetas.id',ondelete='RESTRICT'),nullable=False),sa.Column('almacen_id',U,sa.ForeignKey('sigarh_almacenes.id',ondelete='RESTRICT'),nullable=False),sa.Column('movimiento_id',U,sa.ForeignKey('farmacia_movimientos.id',ondelete='RESTRICT')),sa.Column('estado',sa.String(20),nullable=False),sa.Column('observaciones',sa.Text),sa.Column('dispensado_por',sa.String(255),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False),sa.UniqueConstraint('tenant_id','numero'))
    op.create_table('farmacia_dispensacion_items',sa.Column('id',U,primary_key=True),sa.Column('tenant_id',U,nullable=False),sa.Column('dispensacion_id',U,sa.ForeignKey('farmacia_dispensaciones.id',ondelete='RESTRICT'),nullable=False),sa.Column('receta_item_id',U,sa.ForeignKey('receta_items.id',ondelete='RESTRICT'),nullable=False),sa.Column('lote_id',U,sa.ForeignKey('farmacia_lotes.id',ondelete='RESTRICT'),nullable=False),sa.Column('cantidad',N,nullable=False))
    op.create_table('farmacotecnia_ordenes',sa.Column('id',U,primary_key=True),sa.Column('tenant_id',U,nullable=False),sa.Column('receta_id',U,sa.ForeignKey('recetas.id',ondelete='RESTRICT')),sa.Column('numero',sa.String(40),nullable=False),sa.Column('tipo_requerimiento',sa.String(50),nullable=False),sa.Column('formula',sa.Text,nullable=False),sa.Column('cantidad',N,nullable=False),sa.Column('unidad',sa.String(40),nullable=False),sa.Column('via_administracion',sa.String(80)),sa.Column('estabilidad_horas',sa.Integer),sa.Column('condiciones_conservacion',sa.Text),sa.Column('estado',sa.String(20),nullable=False),sa.Column('responsable',sa.String(255)),sa.Column('control_calidad',sa.JSON,nullable=False),sa.Column('observaciones',sa.Text),sa.Column('created_at',sa.DateTime,nullable=False))
    op.create_table('farmacia_ventas',sa.Column('id',U,primary_key=True),sa.Column('tenant_id',U,nullable=False),sa.Column('numero',sa.String(40),nullable=False),sa.Column('almacen_id',U,sa.ForeignKey('sigarh_almacenes.id',ondelete='RESTRICT'),nullable=False),sa.Column('patient_id',U,sa.ForeignKey('patients.id',ondelete='RESTRICT')),sa.Column('receta_id',U,sa.ForeignKey('recetas.id',ondelete='RESTRICT')),sa.Column('movimiento_id',U,sa.ForeignKey('farmacia_movimientos.id',ondelete='RESTRICT')),sa.Column('tipo_pago',sa.String(30),nullable=False),sa.Column('fuente_financiamiento',sa.String(60),nullable=False),sa.Column('total',N,nullable=False),sa.Column('estado',sa.String(20),nullable=False),sa.Column('registrado_por',sa.String(255),nullable=False),sa.Column('created_at',sa.DateTime,nullable=False))
def downgrade():
    for t in ['farmacia_ventas','farmacotecnia_ordenes','farmacia_dispensacion_items','farmacia_dispensaciones','farmacia_movimiento_items','farmacia_movimientos','farmacia_lotes','farmacia_correlativos','sigarh_catalogos_farmacia','sigarh_proveedores_farmacia']: op.drop_table(t)
