"""crear tablas admision

Revision ID: ad73a93d5ba1
Revises: 92ebb9c0b920
Create Date: 2026-09-02 15:00:17.338644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad73a93d5ba1'
down_revision: Union[str, Sequence[str], None] = '92ebb9c0b920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name_paterno', sa.String(length=100), nullable=False),
    sa.Column('last_name_materno', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('department_id', sa.String(length=2), nullable=True),
    sa.Column('province_id', sa.String(length=4), nullable=True),
    sa.Column('district_id', sa.String(length=6), nullable=True),
    sa.Column('insurance_type', sa.String(length=50), nullable=True),
    sa.Column('insurance_number', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_dni'), 'patients', ['dni'], unique=True)
    op.create_table('clinical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('record_number', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('is_digitized', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_number')
    )
    op.create_table('clinical_record_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinical_record_id', sa.UUID(), nullable=False),
    sa.Column('from_location', sa.String(length=50), nullable=False),
    sa.Column('to_location', sa.String(length=50), nullable=False),
    sa.Column('moved_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinical_record_id'], ['clinical_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clinical_record_movements')
    op.drop_table('clinical_records')
    op.drop_index(op.f('ix_patients_dni'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
