"""hospitalizacion completa: origen emergencia, seguimiento, consentimientos

Revision ID: b6e19a4d5c72
Revises: 7c2d914ef8a3
Create Date: 2026-09-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e19a4d5c72'
down_revision: Union[str, Sequence[str], None] = '7c2d914ef8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- hospitalizaciones: origen dual (Consulta Externa o Emergencia) ---
    op.add_column('hospitalizaciones', sa.Column('atencion_emergencia_id', sa.UUID(), nullable=True))
    op.add_column('hospitalizaciones', sa.Column('patient_id', sa.UUID(), nullable=True))
    op.add_column('hospitalizaciones', sa.Column('registrado_por', sa.String(length=255), nullable=True))
    op.add_column('hospitalizaciones', sa.Column('resumen_alta', sa.Text(), nullable=True))
    op.alter_column('hospitalizaciones', 'atencion_medica_id', existing_type=sa.UUID(), nullable=True)
    op.create_unique_constraint('uq_hospitalizaciones_atencion_emergencia_id', 'hospitalizaciones', ['atencion_emergencia_id'])
    op.create_foreign_key('fk_hosp_atencion_emergencia_id', 'hospitalizaciones', 'atenciones_emergencia', ['atencion_emergencia_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_hosp_patient_id', 'hospitalizaciones', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')

    # Backfill: hospitalizaciones ya existentes (todas de origen Consulta Externa)
    # obtienen su patient_id desde la cadena atencion_medica -> cita.
    op.execute("""
        UPDATE hospitalizaciones h SET patient_id = c.patient_id
        FROM atenciones_medicas a JOIN citas c ON c.id = a.cita_id
        WHERE h.atencion_medica_id = a.id AND h.patient_id IS NULL
    """)

    # --- interconsultas: origen dual (Consulta Externa o Hospitalizacion) ---
    op.add_column('interconsultas', sa.Column('hospitalizacion_id', sa.UUID(), nullable=True))
    op.add_column('interconsultas', sa.Column('solicitado_por', sa.String(length=255), nullable=True))
    op.alter_column('interconsultas', 'atencion_medica_id', existing_type=sa.UUID(), nullable=True)
    op.create_unique_constraint('uq_interconsultas_hospitalizacion_id', 'interconsultas', ['hospitalizacion_id'])
    op.create_foreign_key('fk_interconsulta_hospitalizacion_id', 'interconsultas', 'hospitalizaciones', ['hospitalizacion_id'], ['id'], ondelete='CASCADE')

    # --- tablas nuevas del módulo ---
    op.create_table('hosp_correlativos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'tipo')
    )
    op.create_table('hosp_notas_evolucion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('hospitalizacion_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('pulso', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('presion_sistolica', sa.Integer(), nullable=True),
    sa.Column('presion_diastolica', sa.Integer(), nullable=True),
    sa.Column('frecuencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frecuencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('saturacion_o2', sa.Float(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('plan_indicaciones', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['sigarh_empleados.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hospitalizacion_id'], ['hospitalizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosp_notas_evolucion_created_at'), 'hosp_notas_evolucion', ['created_at'], unique=False)
    op.create_index(op.f('ix_hosp_notas_evolucion_hospitalizacion_id'), 'hosp_notas_evolucion', ['hospitalizacion_id'], unique=False)
    op.create_index(op.f('ix_hosp_notas_evolucion_tenant_id'), 'hosp_notas_evolucion', ['tenant_id'], unique=False)
    op.create_table('hosp_consentimientos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('hospitalizacion_id', sa.UUID(), nullable=False),
    sa.Column('medico_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('procedimiento', sa.String(length=255), nullable=False),
    sa.Column('riesgos_beneficios', sa.Text(), nullable=False),
    sa.Column('firmante_nombre', sa.String(length=255), nullable=False),
    sa.Column('firmante_documento', sa.String(length=20), nullable=False),
    sa.Column('relacion_firmante', sa.String(length=30), nullable=False),
    sa.Column('testigo_nombre', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('motivo_revocacion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospitalizacion_id'], ['hospitalizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medico_id'], ['sigarh_empleados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosp_consentimientos_hospitalizacion_id'), 'hosp_consentimientos', ['hospitalizacion_id'], unique=False)
    op.create_index(op.f('ix_hosp_consentimientos_tenant_id'), 'hosp_consentimientos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hosp_consentimientos_tenant_id'), table_name='hosp_consentimientos')
    op.drop_index(op.f('ix_hosp_consentimientos_hospitalizacion_id'), table_name='hosp_consentimientos')
    op.drop_table('hosp_consentimientos')
    op.drop_index(op.f('ix_hosp_notas_evolucion_tenant_id'), table_name='hosp_notas_evolucion')
    op.drop_index(op.f('ix_hosp_notas_evolucion_hospitalizacion_id'), table_name='hosp_notas_evolucion')
    op.drop_index(op.f('ix_hosp_notas_evolucion_created_at'), table_name='hosp_notas_evolucion')
    op.drop_table('hosp_notas_evolucion')
    op.drop_table('hosp_correlativos')
    op.drop_constraint('fk_interconsulta_hospitalizacion_id', 'interconsultas', type_='foreignkey')
    op.drop_constraint('uq_interconsultas_hospitalizacion_id', 'interconsultas', type_='unique')
    op.alter_column('interconsultas', 'atencion_medica_id', existing_type=sa.UUID(), nullable=False)
    op.drop_column('interconsultas', 'solicitado_por')
    op.drop_column('interconsultas', 'hospitalizacion_id')
    op.drop_constraint('fk_hosp_patient_id', 'hospitalizaciones', type_='foreignkey')
    op.drop_constraint('fk_hosp_atencion_emergencia_id', 'hospitalizaciones', type_='foreignkey')
    op.drop_constraint('uq_hospitalizaciones_atencion_emergencia_id', 'hospitalizaciones', type_='unique')
    op.alter_column('hospitalizaciones', 'atencion_medica_id', existing_type=sa.UUID(), nullable=False)
    op.drop_column('hospitalizaciones', 'resumen_alta')
    op.drop_column('hospitalizaciones', 'registrado_por')
    op.drop_column('hospitalizaciones', 'patient_id')
    op.drop_column('hospitalizaciones', 'atencion_emergencia_id')
    # ### end Alembic commands ###
