"""add cita and generalize programacion medica

Revision ID: bbe1987cc137
Revises: 8aeea41cba23
Create Date: 2026-09-06 17:22:22.845208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe1987cc137'
down_revision: Union[str, Sequence[str], None] = '8aeea41cba23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('programacion_medica_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=False),
    sa.Column('hora_fin', sa.String(length=5), nullable=False),
    sa.Column('tipo_consulta', sa.String(length=50), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=True),
    sa.Column('cuenta_vinculada', sa.String(length=100), nullable=True),
    sa.Column('fuente_financiamiento', sa.String(length=100), nullable=True),
    sa.Column('producto_plan', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programacion_medica_id'], ['programaciones_medicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_tenant_id'), 'citas', ['tenant_id'], unique=False)
    op.add_column('programaciones_medicas', sa.Column('servicio_id', sa.UUID(), nullable=True))
    op.alter_column('programaciones_medicas', 'especialidad_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('programaciones_medicas_especialidad_id_fkey'), 'programaciones_medicas', type_='foreignkey')
    op.create_foreign_key(None, 'programaciones_medicas', 'sigarh_especialidades', ['especialidad_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'programaciones_medicas', 'sigarh_servicios', ['servicio_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'programaciones_medicas', type_='foreignkey')
    op.drop_constraint(None, 'programaciones_medicas', type_='foreignkey')
    op.create_foreign_key(op.f('programaciones_medicas_especialidad_id_fkey'), 'programaciones_medicas', 'sigarh_especialidades', ['especialidad_id'], ['id'], ondelete='CASCADE')
    op.alter_column('programaciones_medicas', 'especialidad_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('programaciones_medicas', 'servicio_id')
    op.drop_index(op.f('ix_citas_tenant_id'), table_name='citas')
    op.drop_table('citas')
    # ### end Alembic commands ###
