"""add orden laboratorio

Revision ID: c54d8211ada0
Revises: cc993fceb4aa
Create Date: 2026-09-07 14:40:54.708945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54d8211ada0'
down_revision: Union[str, Sequence[str], None] = 'cc993fceb4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_laboratorio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('atencion_medica_id', sa.UUID(), nullable=False),
    sa.Column('numero_orden', sa.String(length=30), nullable=False),
    sa.Column('indicacion_clinica', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atencion_medica_id'], ['atenciones_medicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atencion_medica_id'),
    sa.UniqueConstraint('numero_orden')
    )
    op.create_index(op.f('ix_ordenes_laboratorio_tenant_id'), 'ordenes_laboratorio', ['tenant_id'], unique=False)
    op.create_table('orden_laboratorio_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orden_id', sa.UUID(), nullable=False),
    sa.Column('examen_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['examen_id'], ['sigarh_examenes_laboratorio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_laboratorio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden_laboratorio_items')
    op.drop_index(op.f('ix_ordenes_laboratorio_tenant_id'), table_name='ordenes_laboratorio')
    op.drop_table('ordenes_laboratorio')
    # ### end Alembic commands ###
