"""add hospitalizacion

Revision ID: cc993fceb4aa
Revises: 56d11705a3ba
Create Date: 2026-09-06 23:09:33.464212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc993fceb4aa'
down_revision: Union[str, Sequence[str], None] = '56d11705a3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitalizaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('atencion_medica_id', sa.UUID(), nullable=False),
    sa.Column('cama_id', sa.UUID(), nullable=False),
    sa.Column('especialidad_ingreso_id', sa.UUID(), nullable=True),
    sa.Column('diagnostico_ingreso_id', sa.UUID(), nullable=True),
    sa.Column('numero_hospitalizacion', sa.String(length=30), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('fecha_alta', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['atencion_medica_id'], ['atenciones_medicas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cama_id'], ['sigarh_camas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['diagnostico_ingreso_id'], ['sigarh_diagnosticos_cie10.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['especialidad_ingreso_id'], ['sigarh_especialidades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atencion_medica_id'),
    sa.UniqueConstraint('numero_hospitalizacion')
    )
    op.create_index(op.f('ix_hospitalizaciones_tenant_id'), 'hospitalizaciones', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospitalizaciones_tenant_id'), table_name='hospitalizaciones')
    op.drop_table('hospitalizaciones')
    # ### end Alembic commands ###
