"""crear tablas sigarh rrhh

Revision ID: cf095ca1b506
Revises: 81fe50263edc
Create Date: 2026-09-03 09:21:37.025397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf095ca1b506'
down_revision: Union[str, Sequence[str], None] = '81fe50263edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_dias_feriados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_dias_feriados_tenant_id'), 'sigarh_dias_feriados', ['tenant_id'], unique=False)
    op.create_table('sigarh_especialidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_especialidades_tenant_id'), 'sigarh_especialidades', ['tenant_id'], unique=False)
    op.create_table('sigarh_motivos_justificacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_motivos_justificacion_tenant_id'), 'sigarh_motivos_justificacion', ['tenant_id'], unique=False)
    op.create_table('sigarh_tolerancias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('minutos_entrada', sa.Integer(), nullable=False),
    sa.Column('minutos_salida', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_tolerancias_tenant_id'), 'sigarh_tolerancias', ['tenant_id'], unique=False)
    op.create_table('sigarh_empleados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('grupo_sanguineo', sa.String(length=5), nullable=True),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('telefono_fijo', sa.String(length=15), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('tipo_trabajador_id', sa.UUID(), nullable=True),
    sa.Column('nivel_remunerativo_id', sa.UUID(), nullable=True),
    sa.Column('grupo_ocupacional_id', sa.UUID(), nullable=True),
    sa.Column('departamento_id', sa.UUID(), nullable=True),
    sa.Column('servicio_id', sa.UUID(), nullable=True),
    sa.Column('cargo_laboral', sa.String(length=255), nullable=True),
    sa.Column('modalidad', sa.String(length=100), nullable=True),
    sa.Column('codigo_minsa', sa.String(length=50), nullable=True),
    sa.Column('numero_cmp', sa.String(length=50), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_nombramiento', sa.Date(), nullable=True),
    sa.Column('fecha_cese', sa.Date(), nullable=True),
    sa.Column('resolucion_nombramiento', sa.String(length=255), nullable=True),
    sa.Column('resolucion_cese', sa.String(length=255), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('ruc', sa.String(length=11), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=True),
    sa.Column('numero_cci', sa.String(length=50), nullable=True),
    sa.Column('tipo_cuenta', sa.String(length=30), nullable=True),
    sa.Column('departamento_ubigeo', sa.String(length=2), nullable=True),
    sa.Column('provincia_ubigeo', sa.String(length=4), nullable=True),
    sa.Column('distrito_ubigeo', sa.String(length=6), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['sigarh_departamentos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grupo_ocupacional_id'], ['sigarh_grupos_ocupacionales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nivel_remunerativo_id'], ['sigarh_niveles_remunerativos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servicio_id'], ['sigarh_servicios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_trabajador_id'], ['sigarh_tipos_trabajador.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_empleados_dni'), 'sigarh_empleados', ['dni'], unique=False)
    op.create_index(op.f('ix_sigarh_empleados_tenant_id'), 'sigarh_empleados', ['tenant_id'], unique=False)
    op.create_table('sigarh_empleado_especialidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('especialidad_id', sa.UUID(), nullable=False),
    sa.Column('numero_rne', sa.String(length=50), nullable=True),
    sa.Column('certificado_url', sa.Text(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['sigarh_empleados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['especialidad_id'], ['sigarh_especialidades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigarh_justificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('motivo_id', sa.UUID(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('documento_url', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['sigarh_empleados.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motivo_id'], ['sigarh_motivos_justificacion.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_justificaciones_tenant_id'), 'sigarh_justificaciones', ['tenant_id'], unique=False)
    op.create_table('sigarh_registro_asistencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.String(length=5), nullable=True),
    sa.Column('hora_salida', sa.String(length=5), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['sigarh_empleados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_registro_asistencia_tenant_id'), 'sigarh_registro_asistencia', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sigarh_registro_asistencia_tenant_id'), table_name='sigarh_registro_asistencia')
    op.drop_table('sigarh_registro_asistencia')
    op.drop_index(op.f('ix_sigarh_justificaciones_tenant_id'), table_name='sigarh_justificaciones')
    op.drop_table('sigarh_justificaciones')
    op.drop_table('sigarh_empleado_especialidades')
    op.drop_index(op.f('ix_sigarh_empleados_tenant_id'), table_name='sigarh_empleados')
    op.drop_index(op.f('ix_sigarh_empleados_dni'), table_name='sigarh_empleados')
    op.drop_table('sigarh_empleados')
    op.drop_index(op.f('ix_sigarh_tolerancias_tenant_id'), table_name='sigarh_tolerancias')
    op.drop_table('sigarh_tolerancias')
    op.drop_index(op.f('ix_sigarh_motivos_justificacion_tenant_id'), table_name='sigarh_motivos_justificacion')
    op.drop_table('sigarh_motivos_justificacion')
    op.drop_index(op.f('ix_sigarh_especialidades_tenant_id'), table_name='sigarh_especialidades')
    op.drop_table('sigarh_especialidades')
    op.drop_index(op.f('ix_sigarh_dias_feriados_tenant_id'), table_name='sigarh_dias_feriados')
    op.drop_table('sigarh_dias_feriados')
    # ### end Alembic commands ###
