"""referencias completo: origen emergencia, resolucion y contrarreferencia

Revision ID: d4f27b18e903
Revises: b6e19a4d5c72
Create Date: 2026-09-16 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f27b18e903'
down_revision: Union[str, Sequence[str], None] = 'b6e19a4d5c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referencia_correlativos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'tipo')
    )

    op.add_column('referencias', sa.Column('atencion_emergencia_id', sa.UUID(), nullable=True))
    op.add_column('referencias', sa.Column('patient_id', sa.UUID(), nullable=True))
    op.add_column('referencias', sa.Column('registrado_por', sa.String(length=255), nullable=True))
    op.add_column('referencias', sa.Column('observacion_resolucion', sa.Text(), nullable=True))
    op.add_column('referencias', sa.Column('fecha_contrarreferencia', sa.Date(), nullable=True))
    op.add_column('referencias', sa.Column('profesional_receptor', sa.String(length=255), nullable=True))
    op.add_column('referencias', sa.Column('diagnostico_contrarreferencia_id', sa.UUID(), nullable=True))
    op.add_column('referencias', sa.Column('resumen_contrarreferencia', sa.Text(), nullable=True))
    op.alter_column('referencias', 'atencion_medica_id', existing_type=sa.UUID(), nullable=True)
    op.create_unique_constraint('uq_referencias_atencion_emergencia_id', 'referencias', ['atencion_emergencia_id'])
    op.create_foreign_key('fk_referencia_atencion_emergencia_id', 'referencias', 'atenciones_emergencia', ['atencion_emergencia_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_referencia_patient_id', 'referencias', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_referencia_diagnostico_contrarreferencia_id', 'referencias', 'sigarh_diagnosticos_cie10', ['diagnostico_contrarreferencia_id'], ['id'], ondelete='SET NULL')

    # Backfill: referencias ya existentes (todas de origen Consulta Externa)
    # obtienen su patient_id desde la cadena atencion_medica -> cita.
    op.execute("""
        UPDATE referencias r SET patient_id = c.patient_id
        FROM atenciones_medicas a JOIN citas c ON c.id = a.cita_id
        WHERE r.atencion_medica_id = a.id AND r.patient_id IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_referencia_diagnostico_contrarreferencia_id', 'referencias', type_='foreignkey')
    op.drop_constraint('fk_referencia_patient_id', 'referencias', type_='foreignkey')
    op.drop_constraint('fk_referencia_atencion_emergencia_id', 'referencias', type_='foreignkey')
    op.drop_constraint('uq_referencias_atencion_emergencia_id', 'referencias', type_='unique')
    op.alter_column('referencias', 'atencion_medica_id', existing_type=sa.UUID(), nullable=False)
    op.drop_column('referencias', 'resumen_contrarreferencia')
    op.drop_column('referencias', 'diagnostico_contrarreferencia_id')
    op.drop_column('referencias', 'profesional_receptor')
    op.drop_column('referencias', 'fecha_contrarreferencia')
    op.drop_column('referencias', 'observacion_resolucion')
    op.drop_column('referencias', 'registrado_por')
    op.drop_column('referencias', 'patient_id')
    op.drop_column('referencias', 'atencion_emergencia_id')
    op.drop_table('referencia_correlativos')
    # ### end Alembic commands ###
