"""crear tablas sigarh infraestructura

Revision ID: d6a49170b21b
Revises: 0ade2c30aedb
Create Date: 2026-09-03 16:01:20.126799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a49170b21b'
down_revision: Union[str, Sequence[str], None] = '0ade2c30aedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_catalogos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_catalogos_categoria'), 'sigarh_catalogos', ['categoria'], unique=False)
    op.create_index(op.f('ix_sigarh_catalogos_tenant_id'), 'sigarh_catalogos', ['tenant_id'], unique=False)
    op.create_table('sigarh_consultorios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('especialidad_id', sa.UUID(), nullable=True),
    sa.Column('piso_id', sa.UUID(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('equipamiento', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['sigarh_especialidades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_consultorios_tenant_id'), 'sigarh_consultorios', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sigarh_consultorios_tenant_id'), table_name='sigarh_consultorios')
    op.drop_table('sigarh_consultorios')
    op.drop_index(op.f('ix_sigarh_catalogos_tenant_id'), table_name='sigarh_catalogos')
    op.drop_index(op.f('ix_sigarh_catalogos_categoria'), table_name='sigarh_catalogos')
    op.drop_table('sigarh_catalogos')
    # ### end Alembic commands ###
