"""laboratorio movimientos cupos resultados covid

Revision ID: d6ffc75e66ac
Revises: df145dce7707
Create Date: 2026-09-08 15:19:01.823219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6ffc75e66ac'
down_revision: Union[str, Sequence[str], None] = 'df145dce7707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_correlativos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'tipo')
    )
    op.create_table('lab_cupos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cupos', sa.Integer(), nullable=False),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cupos >= 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'fecha')
    )
    op.create_index(op.f('ix_lab_cupos_tenant_id'), 'lab_cupos', ['tenant_id'], unique=False)
    op.create_table('lab_fichas_covid',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_prueba', sa.String(length=100), nullable=False),
    sa.Column('muestra', sa.String(length=100), nullable=False),
    sa.Column('resultado', sa.String(length=30), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_fichas_covid_fecha'), 'lab_fichas_covid', ['fecha'], unique=False)
    op.create_index(op.f('ix_lab_fichas_covid_tenant_id'), 'lab_fichas_covid', ['tenant_id'], unique=False)
    op.create_table('lab_movimientos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('orden_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('toma_examen_id', sa.UUID(), nullable=False),
    sa.Column('agendamiento_por', sa.String(length=40), nullable=False),
    sa.Column('registrar_por', sa.String(length=30), nullable=False),
    sa.Column('cuenta_nueva', sa.Boolean(), nullable=False),
    sa.Column('comprobante', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('toma_at', sa.DateTime(), nullable=True),
    sa.Column('validado_at', sa.DateTime(), nullable=True),
    sa.Column('validado_por', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_laboratorio.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['toma_examen_id'], ['sigarh_empleados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden_id'),
    sa.UniqueConstraint('tenant_id', 'numero')
    )
    op.create_index(op.f('ix_lab_movimientos_fecha'), 'lab_movimientos', ['fecha'], unique=False)
    op.create_index(op.f('ix_lab_movimientos_tenant_id'), 'lab_movimientos', ['tenant_id'], unique=False)
    op.create_table('lab_movimiento_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('movimiento_id', sa.UUID(), nullable=False),
    sa.Column('examen_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo_muestra', sa.String(length=100), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('referencia', sa.Text(), nullable=True),
    sa.Column('resultados', sa.JSON(), nullable=False),
    sa.CheckConstraint('cantidad > 0'),
    sa.CheckConstraint('precio >= 0'),
    sa.ForeignKeyConstraint(['examen_id'], ['sigarh_examenes_laboratorio.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movimiento_id'], ['lab_movimientos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimiento_id', 'examen_id')
    )
    op.create_index(op.f('ix_lab_movimiento_items_tenant_id'), 'lab_movimiento_items', ['tenant_id'], unique=False)
    op.add_column('ordenes_laboratorio', sa.Column('patient_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_laboratorio', sa.Column('emergencia_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_laboratorio', sa.Column('tipo_servicio', sa.String(length=30), server_default='CONSULTA_EXTERNA', nullable=False))
    op.add_column('ordenes_laboratorio', sa.Column('servicio_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_laboratorio', sa.Column('especialidad_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_laboratorio', sa.Column('medico_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_laboratorio', sa.Column('numero_cuenta', sa.String(length=50), nullable=True))
    op.add_column('ordenes_laboratorio', sa.Column('fuente_financiamiento', sa.String(length=100), nullable=True))
    op.add_column('ordenes_laboratorio', sa.Column('registrado_por', sa.String(length=255), nullable=True))
    op.alter_column('ordenes_laboratorio', 'atencion_medica_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('fk_lab_orden_medico_id', 'ordenes_laboratorio', 'sigarh_empleados', ['medico_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_lab_orden_especialidad_id', 'ordenes_laboratorio', 'sigarh_especialidades', ['especialidad_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_lab_orden_patient_id', 'ordenes_laboratorio', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_lab_orden_servicio_id', 'ordenes_laboratorio', 'sigarh_servicios', ['servicio_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_lab_orden_emergencia_id', 'ordenes_laboratorio', 'admisiones_emergencia', ['emergencia_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lab_orden_medico_id', 'ordenes_laboratorio', type_='foreignkey')
    op.drop_constraint('fk_lab_orden_especialidad_id', 'ordenes_laboratorio', type_='foreignkey')
    op.drop_constraint('fk_lab_orden_patient_id', 'ordenes_laboratorio', type_='foreignkey')
    op.drop_constraint('fk_lab_orden_servicio_id', 'ordenes_laboratorio', type_='foreignkey')
    op.drop_constraint('fk_lab_orden_emergencia_id', 'ordenes_laboratorio', type_='foreignkey')
    op.alter_column('ordenes_laboratorio', 'atencion_medica_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ordenes_laboratorio', 'registrado_por')
    op.drop_column('ordenes_laboratorio', 'fuente_financiamiento')
    op.drop_column('ordenes_laboratorio', 'numero_cuenta')
    op.drop_column('ordenes_laboratorio', 'medico_id')
    op.drop_column('ordenes_laboratorio', 'especialidad_id')
    op.drop_column('ordenes_laboratorio', 'servicio_id')
    op.drop_column('ordenes_laboratorio', 'tipo_servicio')
    op.drop_column('ordenes_laboratorio', 'emergencia_id')
    op.drop_column('ordenes_laboratorio', 'patient_id')
    op.drop_index(op.f('ix_lab_movimiento_items_tenant_id'), table_name='lab_movimiento_items')
    op.drop_table('lab_movimiento_items')
    op.drop_index(op.f('ix_lab_movimientos_tenant_id'), table_name='lab_movimientos')
    op.drop_index(op.f('ix_lab_movimientos_fecha'), table_name='lab_movimientos')
    op.drop_table('lab_movimientos')
    op.drop_index(op.f('ix_lab_fichas_covid_tenant_id'), table_name='lab_fichas_covid')
    op.drop_index(op.f('ix_lab_fichas_covid_fecha'), table_name='lab_fichas_covid')
    op.drop_table('lab_fichas_covid')
    op.drop_index(op.f('ix_lab_cupos_tenant_id'), table_name='lab_cupos')
    op.drop_table('lab_cupos')
    op.drop_table('lab_correlativos')
    # ### end Alembic commands ###

