"""add emergencia

Revision ID: df145dce7707
Revises: 428bfcb15e01
Create Date: 2026-09-07 16:59:39.549136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df145dce7707'
down_revision: Union[str, Sequence[str], None] = '428bfcb15e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admisiones_emergencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=30), nullable=False),
    sa.Column('servicio_emergencia', sa.String(length=100), nullable=False),
    sa.Column('fuente_financiamiento', sa.String(length=100), nullable=True),
    sa.Column('acompanante_nombre', sa.String(length=255), nullable=True),
    sa.Column('acompanante_documento', sa.String(length=20), nullable=True),
    sa.Column('acompanante_parentesco', sa.String(length=50), nullable=True),
    sa.Column('acompanante_telefono', sa.String(length=20), nullable=True),
    sa.Column('acompanante_direccion', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_cuenta')
    )
    op.create_index(op.f('ix_admisiones_emergencia_tenant_id'), 'admisiones_emergencia', ['tenant_id'], unique=False)
    op.create_table('atenciones_emergencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('admision_id', sa.UUID(), nullable=False),
    sa.Column('medico_id', sa.UUID(), nullable=True),
    sa.Column('motivo_consulta', sa.Text(), nullable=False),
    sa.Column('examen_clinico', sa.Text(), nullable=True),
    sa.Column('plan_tratamiento', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('destino_atencion', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('firmado_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admision_id'], ['admisiones_emergencia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medico_id'], ['sigarh_empleados.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admision_id')
    )
    op.create_index(op.f('ix_atenciones_emergencia_tenant_id'), 'atenciones_emergencia', ['tenant_id'], unique=False)
    op.create_table('triajes_emergencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('admision_id', sa.UUID(), nullable=False),
    sa.Column('prioridad', sa.String(length=5), nullable=False),
    sa.Column('pulso', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('presion_sistolica', sa.Integer(), nullable=True),
    sa.Column('presion_diastolica', sa.Integer(), nullable=True),
    sa.Column('frecuencia_cardiaca', sa.Integer(), nullable=True),
    sa.Column('frecuencia_respiratoria', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('talla', sa.Float(), nullable=True),
    sa.Column('saturacion_o2', sa.Float(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admision_id'], ['admisiones_emergencia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admision_id')
    )
    op.create_index(op.f('ix_triajes_emergencia_tenant_id'), 'triajes_emergencia', ['tenant_id'], unique=False)
    op.create_table('emergencia_diagnosticos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('atencion_emergencia_id', sa.UUID(), nullable=False),
    sa.Column('diagnostico_cie10_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atencion_emergencia_id'], ['atenciones_emergencia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['diagnostico_cie10_id'], ['sigarh_diagnosticos_cie10.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergencia_diagnosticos')
    op.drop_index(op.f('ix_triajes_emergencia_tenant_id'), table_name='triajes_emergencia')
    op.drop_table('triajes_emergencia')
    op.drop_index(op.f('ix_atenciones_emergencia_tenant_id'), table_name='atenciones_emergencia')
    op.drop_table('atenciones_emergencia')
    op.drop_index(op.f('ix_admisiones_emergencia_tenant_id'), table_name='admisiones_emergencia')
    op.drop_table('admisiones_emergencia')
    # ### end Alembic commands ###
