"""add receta farmacia

Revision ID: e268d127e63d
Revises: efb3fa124a78
Create Date: 2026-09-06 20:55:50.607014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e268d127e63d'
down_revision: Union[str, Sequence[str], None] = 'efb3fa124a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('atencion_medica_id', sa.UUID(), nullable=False),
    sa.Column('numero_receta', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['atencion_medica_id'], ['atenciones_medicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atencion_medica_id'),
    sa.UniqueConstraint('numero_receta')
    )
    op.create_index(op.f('ix_recetas_tenant_id'), 'recetas', ['tenant_id'], unique=False)
    op.create_table('receta_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receta_id', sa.UUID(), nullable=False),
    sa.Column('medicamento_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('dosis', sa.String(length=100), nullable=True),
    sa.Column('frecuencia', sa.String(length=100), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('indicaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['sigarh_medicamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receta_items')
    op.drop_index(op.f('ix_recetas_tenant_id'), table_name='recetas')
    op.drop_table('recetas')
    # ### end Alembic commands ###
