"""replace tipo_grupo FK with simple UUID

Revision ID: eb38ca19b28e
Revises: 7bbc7df736cd
Create Date: 2026-09-07 12:14:39.237232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb38ca19b28e'
down_revision: Union[str, Sequence[str], None] = '7bbc7df736cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint(op.f('sigarh_grupos_ocupacionales_tipo_grupo_id_fkey'), 'sigarh_grupos_ocupacionales', type_='foreignkey')
    op.drop_index(op.f('ix_sigarh_tipos_grupo_ocupacional_tenant_id'), table_name='sigarh_tipos_grupo_ocupacional')
    op.drop_table('sigarh_tipos_grupo_ocupacional')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('sigarh_grupos_ocupacionales_tipo_grupo_id_fkey'), 'sigarh_grupos_ocupacionales', 'sigarh_tipos_grupo_ocupacional', ['tipo_grupo_id'], ['id'], ondelete='SET NULL')
    op.create_table('sigarh_tipos_grupo_ocupacional',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sigarh_tipos_grupo_ocupacional_pkey'))
    )
    op.create_index(op.f('ix_sigarh_tipos_grupo_ocupacional_tenant_id'), 'sigarh_tipos_grupo_ocupacional', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
