"""add antecedentes to patient

Revision ID: efb3fa124a78
Revises: 30a09d217780
Create Date: 2026-09-06 20:23:08.687098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb3fa124a78'
down_revision: Union[str, Sequence[str], None] = '30a09d217780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('antecedente_quirurgico', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('antecedente_patologico', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('antecedente_alergias', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('antecedentes_obstetricos', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('antecedente_familiares', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('antecedente_otros', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'antecedente_otros')
    op.drop_column('patients', 'antecedente_familiares')
    op.drop_column('patients', 'antecedentes_obstetricos')
    op.drop_column('patients', 'antecedente_alergias')
    op.drop_column('patients', 'antecedente_patologico')
    op.drop_column('patients', 'antecedente_quirurgico')
    # ### end Alembic commands ###
