"""add piso_id to servicio

Revision ID: f378f23755f9
Revises: 82f0eac622dc
Create Date: 2026-09-07 09:56:43.662998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f378f23755f9'
down_revision: Union[str, Sequence[str], None] = '82f0eac622dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sigarh_servicios', sa.Column('piso_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sigarh_servicios', 'sigarh_pisos', ['piso_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sigarh_servicios', type_='foreignkey')
    op.drop_column('sigarh_servicios', 'piso_id')
    # ### end Alembic commands ###
