"""imagenologia movimientos e informes

Revision ID: f3a8c92e6d17
Revises: 0c824b51ab69
Create Date: 2026-09-14 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a8c92e6d17'
down_revision: Union[str, Sequence[str], None] = '0c824b51ab69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagen_correlativos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'tipo')
    )
    op.create_table('imagen_movimientos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('orden_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tecnico_id', sa.UUID(), nullable=False),
    sa.Column('agendamiento_por', sa.String(length=40), nullable=False),
    sa.Column('registrar_por', sa.String(length=30), nullable=False),
    sa.Column('cuenta_nueva', sa.Boolean(), nullable=False),
    sa.Column('comprobante', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo_anulacion', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.String(length=255), nullable=False),
    sa.Column('toma_at', sa.DateTime(), nullable=True),
    sa.Column('validado_at', sa.DateTime(), nullable=True),
    sa.Column('validado_por', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_imagen.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['sigarh_empleados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden_id'),
    sa.UniqueConstraint('tenant_id', 'numero')
    )
    op.create_index(op.f('ix_imagen_movimientos_fecha'), 'imagen_movimientos', ['fecha'], unique=False)
    op.create_index(op.f('ix_imagen_movimientos_tenant_id'), 'imagen_movimientos', ['tenant_id'], unique=False)
    op.create_table('imagen_movimiento_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('movimiento_id', sa.UUID(), nullable=False),
    sa.Column('examen_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('modalidad', sa.String(length=100), nullable=True),
    sa.Column('parte_cuerpo', sa.String(length=100), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tecnica', sa.Text(), nullable=True),
    sa.Column('hallazgos', sa.Text(), nullable=True),
    sa.Column('impresion_diagnostica', sa.Text(), nullable=True),
    sa.CheckConstraint('cantidad > 0', name='imagen_movimiento_items_cantidad_check'),
    sa.CheckConstraint('precio >= 0', name='imagen_movimiento_items_precio_check'),
    sa.ForeignKeyConstraint(['examen_id'], ['sigarh_examenes_imagenologia.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movimiento_id'], ['imagen_movimientos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimiento_id', 'examen_id')
    )
    op.create_index(op.f('ix_imagen_movimiento_items_tenant_id'), 'imagen_movimiento_items', ['tenant_id'], unique=False)
    op.add_column('ordenes_imagen', sa.Column('patient_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_imagen', sa.Column('emergencia_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_imagen', sa.Column('tipo_servicio', sa.String(length=30), server_default='CONSULTA_EXTERNA', nullable=False))
    op.add_column('ordenes_imagen', sa.Column('servicio_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_imagen', sa.Column('especialidad_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_imagen', sa.Column('medico_id', sa.UUID(), nullable=True))
    op.add_column('ordenes_imagen', sa.Column('numero_cuenta', sa.String(length=50), nullable=True))
    op.add_column('ordenes_imagen', sa.Column('fuente_financiamiento', sa.String(length=100), nullable=True))
    op.add_column('ordenes_imagen', sa.Column('registrado_por', sa.String(length=255), nullable=True))
    op.alter_column('ordenes_imagen', 'atencion_medica_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('fk_img_orden_medico_id', 'ordenes_imagen', 'sigarh_empleados', ['medico_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_img_orden_especialidad_id', 'ordenes_imagen', 'sigarh_especialidades', ['especialidad_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_img_orden_patient_id', 'ordenes_imagen', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_img_orden_servicio_id', 'ordenes_imagen', 'sigarh_servicios', ['servicio_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_img_orden_emergencia_id', 'ordenes_imagen', 'admisiones_emergencia', ['emergencia_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_img_orden_medico_id', 'ordenes_imagen', type_='foreignkey')
    op.drop_constraint('fk_img_orden_especialidad_id', 'ordenes_imagen', type_='foreignkey')
    op.drop_constraint('fk_img_orden_patient_id', 'ordenes_imagen', type_='foreignkey')
    op.drop_constraint('fk_img_orden_servicio_id', 'ordenes_imagen', type_='foreignkey')
    op.drop_constraint('fk_img_orden_emergencia_id', 'ordenes_imagen', type_='foreignkey')
    op.alter_column('ordenes_imagen', 'atencion_medica_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ordenes_imagen', 'registrado_por')
    op.drop_column('ordenes_imagen', 'fuente_financiamiento')
    op.drop_column('ordenes_imagen', 'numero_cuenta')
    op.drop_column('ordenes_imagen', 'medico_id')
    op.drop_column('ordenes_imagen', 'especialidad_id')
    op.drop_column('ordenes_imagen', 'servicio_id')
    op.drop_column('ordenes_imagen', 'tipo_servicio')
    op.drop_column('ordenes_imagen', 'emergencia_id')
    op.drop_column('ordenes_imagen', 'patient_id')
    op.drop_index(op.f('ix_imagen_movimiento_items_tenant_id'), table_name='imagen_movimiento_items')
    op.drop_table('imagen_movimiento_items')
    op.drop_index(op.f('ix_imagen_movimientos_tenant_id'), table_name='imagen_movimientos')
    op.drop_index(op.f('ix_imagen_movimientos_fecha'), table_name='imagen_movimientos')
    op.drop_table('imagen_movimientos')
    op.drop_table('imagen_correlativos')
    # ### end Alembic commands ###
