"""general y nutricion sigarh

Revision ID: f43ee115cbbc
Revises: 15bf772826d7
Create Date: 2026-09-04 09:11:21.308868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43ee115cbbc'
down_revision: Union[str, Sequence[str], None] = '15bf772826d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_cambios_turno_nutricion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('turno_saliente', sa.String(length=100), nullable=False),
    sa.Column('turno_entrante', sa.String(length=100), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('raciones_entregadas', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_cambios_turno_nutricion_tenant_id'), 'sigarh_cambios_turno_nutricion', ['tenant_id'], unique=False)
    op.create_table('sigarh_diagnosticos_cie10',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('capitulo', sa.String(length=100), nullable=True),
    sa.Column('grupo', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('codigo_cie10', sa.String(length=20), nullable=False),
    sa.Column('codigo_cie9', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=True),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('edad_minima', sa.Integer(), nullable=True),
    sa.Column('edad_maxima', sa.Integer(), nullable=True),
    sa.Column('morbilidad', sa.Boolean(), nullable=False),
    sa.Column('intrahospitalario', sa.Boolean(), nullable=False),
    sa.Column('gestacion', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_diagnosticos_cie10_codigo_cie10'), 'sigarh_diagnosticos_cie10', ['codigo_cie10'], unique=False)
    op.create_index(op.f('ix_sigarh_diagnosticos_cie10_tenant_id'), 'sigarh_diagnosticos_cie10', ['tenant_id'], unique=False)
    op.create_table('sigarh_raciones_nutricion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('dependencia', sa.String(length=255), nullable=False),
    sa.Column('tipo_racion', sa.String(length=100), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=False),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_raciones_nutricion_dni'), 'sigarh_raciones_nutricion', ['dni'], unique=False)
    op.create_index(op.f('ix_sigarh_raciones_nutricion_tenant_id'), 'sigarh_raciones_nutricion', ['tenant_id'], unique=False)
    op.create_table('sigarh_paquetes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('punto_carga', sa.String(length=100), nullable=True),
    sa.Column('especialidad_id', sa.UUID(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['sigarh_especialidades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_paquetes_tenant_id'), 'sigarh_paquetes', ['tenant_id'], unique=False)
    op.create_table('sigarh_tiempos_procedimientos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('especialidad_id', sa.UUID(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['sigarh_especialidades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_tiempos_procedimientos_tenant_id'), 'sigarh_tiempos_procedimientos', ['tenant_id'], unique=False)
    op.create_table('sigarh_paquete_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paquete_id', sa.UUID(), nullable=False),
    sa.Column('medicamento_id', sa.UUID(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['sigarh_medicamentos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paquete_id'], ['sigarh_paquetes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sigarh_paquete_items')
    op.drop_index(op.f('ix_sigarh_tiempos_procedimientos_tenant_id'), table_name='sigarh_tiempos_procedimientos')
    op.drop_table('sigarh_tiempos_procedimientos')
    op.drop_index(op.f('ix_sigarh_paquetes_tenant_id'), table_name='sigarh_paquetes')
    op.drop_table('sigarh_paquetes')
    op.drop_index(op.f('ix_sigarh_raciones_nutricion_tenant_id'), table_name='sigarh_raciones_nutricion')
    op.drop_index(op.f('ix_sigarh_raciones_nutricion_dni'), table_name='sigarh_raciones_nutricion')
    op.drop_table('sigarh_raciones_nutricion')
    op.drop_index(op.f('ix_sigarh_diagnosticos_cie10_tenant_id'), table_name='sigarh_diagnosticos_cie10')
    op.drop_index(op.f('ix_sigarh_diagnosticos_cie10_codigo_cie10'), table_name='sigarh_diagnosticos_cie10')
    op.drop_table('sigarh_diagnosticos_cie10')
    op.drop_index(op.f('ix_sigarh_cambios_turno_nutricion_tenant_id'), table_name='sigarh_cambios_turno_nutricion')
    op.drop_table('sigarh_cambios_turno_nutricion')
    # ### end Alembic commands ###
