"""crear tablas sigarh config financiera

Revision ID: f5a3c3eee53f
Revises: 04e01279b70c
Create Date: 2026-09-03 16:18:11.780115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a3c3eee53f'
down_revision: Union[str, Sequence[str], None] = '04e01279b70c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sigarh_cajas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('cajero_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('monto_apertura', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_cajas_tenant_id'), 'sigarh_cajas', ['tenant_id'], unique=False)
    op.create_table('sigarh_seguros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('tipo_entidad', sa.String(length=100), nullable=True),
    sa.Column('requiere_fua', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_seguros_tenant_id'), 'sigarh_seguros', ['tenant_id'], unique=False)
    op.create_table('sigarh_planes_seguro',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seguro_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('precio_referencia', sa.Float(), nullable=True),
    sa.Column('detalle_cobertura', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seguro_id'], ['sigarh_seguros.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigarh_tarifario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion_servicio', sa.String(length=255), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=100), nullable=True),
    sa.Column('especialidad_id', sa.UUID(), nullable=True),
    sa.Column('seguro_id', sa.UUID(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['especialidad_id'], ['sigarh_especialidades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seguro_id'], ['sigarh_seguros.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sigarh_tarifario_tenant_id'), 'sigarh_tarifario', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sigarh_tarifario_tenant_id'), table_name='sigarh_tarifario')
    op.drop_table('sigarh_tarifario')
    op.drop_table('sigarh_planes_seguro')
    op.drop_index(op.f('ix_sigarh_seguros_tenant_id'), table_name='sigarh_seguros')
    op.drop_table('sigarh_seguros')
    op.drop_index(op.f('ix_sigarh_cajas_tenant_id'), table_name='sigarh_cajas')
    op.drop_table('sigarh_cajas')
    # ### end Alembic commands ###
