<script setup lang="ts">
definePageMeta({layout:'sigarh',middleware:['auth']})
const {api}=useApi(),route=useRoute(),router=useRouter(),id=computed(()=>route.params.id as string)
const loading=ref(true),saving=ref(false),deleting=ref(false),error=ref(''),item=ref<any>(null),bases=ref<any[]>([])
const form=reactive({nombre:'',codigo:'',descripcion:'',tipo:'especialidad',parent_id:'',is_active:false})
async function guardar(){saving.value=true;error.value='';try{const body=item.value.es_oficial?{descripcion:form.descripcion||null,is_active:form.is_active}:{...form,codigo:form.codigo||null,descripcion:form.descripcion||null,parent_id:form.tipo==='subespecialidad'?form.parent_id:null};await api(`/sigarh/rrhh/especialidades/${id.value}`,{method:'PATCH',body});router.push('/sigarh/rrhh/especialidades')}catch(e:any){error.value=apiErr(e,'No se pudo guardar')}finally{saving.value=false}}
async function eliminar(){if(!confirm(`¿Eliminar "${item.value.nombre}"?`))return;deleting.value=true;try{await api(`/sigarh/rrhh/especialidades/${id.value}`,{method:'DELETE'});router.push('/sigarh/rrhh/especialidades')}catch(e:any){error.value=apiErr(e,'No se pudo eliminar')}finally{deleting.value=false}}
onMounted(async()=>{try{const all=await api<any[]>('/sigarh/rrhh/especialidades');item.value=all.find(e=>e.id===id.value);if(!item.value)throw new Error();bases.value=all.filter(e=>e.tipo==='especialidad'&&e.id!==id.value);Object.assign(form,{nombre:item.value.nombre,codigo:item.value.codigo||'',descripcion:item.value.descripcion||'',tipo:item.value.tipo,parent_id:item.value.parent_id||'',is_active:item.value.is_active})}catch(e:any){error.value=apiErr(e,'No se pudo cargar')}finally{loading.value=false}})
</script>
<template><SFormLayout><template #main>
  <div class="mb-8"><NuxtLink to="/sigarh/rrhh/especialidades" class="text-sm hover:underline" style="color:var(--ink-soft)">← Especialidades y subespecialidades</NuxtLink><h1 class="page-title mt-3">{{item?.nombre||'Detalle'}}</h1><p class="page-subtitle">{{item?.es_oficial?'Configura la disponibilidad del registro oficial':'Edita el registro propio del hospital'}}</p></div>
  <div v-if="loading" class="form-card py-16 text-center">Cargando...</div>
  <SFormCard v-else-if="item" :title="item.es_oficial?'Registro oficial CONAREME':'Registro del hospital'" :subtitle="item.es_oficial?'Su denominación y jerarquía están protegidas':'Puede editarse mientras respete sus relaciones'" :icon="item.es_oficial?'i-heroicons-shield-check':'i-heroicons-building-office-2'" icon-bg="var(--purple-soft)" icon-color="var(--purple)" :error="error">
    <div class="form-group"><label class="form-label">Tipo</label><select v-model="form.tipo" class="input-clinical" :disabled="item.es_oficial" @change="form.parent_id='' "><option value="especialidad">Especialidad</option><option value="subespecialidad">Subespecialidad</option></select></div>
    <div v-if="form.tipo==='subespecialidad'" class="form-group"><label class="form-label">Especialidad principal</label><select v-model="form.parent_id" class="input-clinical" :disabled="item.es_oficial"><option value="">Seleccione...</option><option v-for="base in bases" :key="base.id" :value="base.id">{{base.nombre}}</option></select></div>
    <div class="form-group full-width"><label class="form-label">Nombre</label><input v-model="form.nombre" class="input-clinical" :disabled="item.es_oficial" /></div>
    <div class="form-group"><label class="form-label">Código</label><input v-model="form.codigo" class="input-clinical font-mono-data" :disabled="item.es_oficial" /></div>
    <div class="form-group"><label class="form-label">Estado</label><div class="status-toggle"><span class="toggle-label">Disponible en SIGARH y APP</span><button type="button" class="toggle-switch" :class="{'toggle-active':form.is_active}" @click="form.is_active=!form.is_active"><span class="toggle-slider" /></button></div></div>
    <div class="form-group full-width"><label class="form-label">Descripción / notas</label><textarea v-model="form.descripcion" class="input-clinical" rows="3" /></div>
    <template #actions><div class="flex justify-between w-full"><button v-if="!item.es_oficial" type="button" class="btn-outline" style="color:var(--alert)" :disabled="deleting" @click="eliminar">{{deleting?'Eliminando...':'Eliminar'}}</button><span v-else></span><SFormActions :saving="saving" save-text="Guardar cambios" saving-text="Guardando..." cancel-to="/sigarh/rrhh/especialidades" @save="guardar" /></div></template>
  </SFormCard>
</template><template #sidebar><SWidgetInfo v-if="item" :items="[item.es_oficial?`Fuente: ${item.fuente}`:'Fuente: configuración propia',item.parent_nombre?`Especialidad principal: ${item.parent_nombre}`:'Especialidad principal',`${item.medicos_asignados} asignaciones de personal`]"/><SWidgetTip text="Al desactivar una opción se oculta de los nuevos registros de APP y se conserva su historial."/></template></SFormLayout></template>
